// Generated by scripts/gen-css-types.ts from notice.module.scss. Do not edit.
declare const styles: {
  readonly bar: string;
  readonly body: string;
  readonly chevron: string;
  readonly divided: string;
  readonly icon: string;
  readonly label: string;
  readonly lead: string;
  readonly line: string;
  readonly list: string;
  readonly roll: string;
  readonly stacked: string;
  readonly text: string;
};
export default styles;
