#!/usr/bin/env bash
# Put the stack back on a known set of images.
#
#   deploy/next/rollback.sh --last-upgrade          # the images the last upgrade replaced
#   deploy/next/rollback.sh --web … --worker … --edge …
#   deploy/next/rollback.sh --last-upgrade --restore <dump.sql.gz>
#
# Replacing containers never changes database contents. `--restore` is the one
# thing in this directory that does, it is never implied, and it prints what it
# is about to overwrite and requires `--yes` to proceed unattended. Image
# rollback and data recovery are separate operations and this script reports
# them separately.
#
# Exit codes: 0 rolled back · 1 the target did not come up (the previously
#             running images were restored) · 2 misuse · 3 needs a human.
set -Eeuo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
. "$here/lib/common.sh"
# shellcheck source=lib/readiness.sh
. "$here/lib/readiness.sh"

use_manifest=0
web_target=''
worker_target=''
edge_target=''
restore_file=''
assume_yes=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --last-upgrade) use_manifest=1 ;;
    --web)
      web_target="${2:?--web needs an image}"
      shift
      ;;
    --web=*) web_target="${1#*=}" ;;
    --worker)
      worker_target="${2:?--worker needs an image}"
      shift
      ;;
    --worker=*) worker_target="${1#*=}" ;;
    --edge)
      edge_target="${2:?--edge needs an image}"
      shift
      ;;
    --edge=*) edge_target="${1#*=}" ;;
    --restore)
      restore_file="${2:?--restore needs a dump}"
      shift
      ;;
    --restore=*) restore_file="${1#*=}" ;;
    --yes) assume_yes=1 ;;
    -h | --help)
      sed -n '2,10p' "$0"
      exit 0
      ;;
    *)
      warn "unknown argument: $1"
      exit 2
      ;;
  esac
  shift
done

require_settings

backup_dir="${NEXT_BACKUP_DIR:-$(setting NEXT_BACKUP_DIR)}"
backup_dir="${backup_dir:-$deploy_root/data/backups}"
case "$backup_dir" in /*) ;; *) backup_dir="$deploy_root/${backup_dir#./}" ;; esac

declare -A want_ref want_id
manifest=''
if [ "$use_manifest" -eq 1 ]; then
  [ -z "$web_target$worker_target$edge_target" ] ||
    die '--last-upgrade and explicit images are mutually exclusive'
  # shellcheck disable=SC2012  # these names are generated by upgrade.sh
  # (`upgrade-<utc stamp>-<pid>.manifest`); there is nothing odd to handle.
  manifest="$(ls -t "$backup_dir"/upgrade-*.manifest 2>/dev/null | head -n1 || true)"
  [ -n "$manifest" ] || die "no upgrade manifest in $backup_dir"
  say "manifest: $manifest"
  for service in $APP_SERVICES; do
    want_ref["$service"]="$(sed -n "s/^previous_$service=//p" "$manifest")"
    want_id["$service"]="$(sed -n "s/^previous_${service}_id=//p" "$manifest")"
    [ -n "${want_ref[$service]}" ] ||
      die "the manifest has no previous image for $service: $manifest"
  done
else
  if [ -z "$web_target" ] || [ -z "$worker_target" ] || [ -z "$edge_target" ]; then
    die 'give --last-upgrade, or all three of --web / --worker / --edge'
  fi
  want_ref[web]="$web_target"
  want_ref[worker]="$worker_target"
  want_ref[edge]="$edge_target"
  for service in $APP_SERVICES; do
    want_id["$service"]=''
    is_digest_ref "${want_ref[$service]}" || [ "${NEXT_ALLOW_LOCAL_IMAGES:-0}" = '1' ] ||
      die "the $service target must be pinned by digest: ${want_ref[$service]}"
  done
fi

# --- what is running now, so a failed rollback can be undone -----------------
declare -A current_ref current_id
for service in $APP_SERVICES; do
  if captured="$(running_image_ref "$service")"; then
    current_ref["$service"]="${captured%% *}"
    current_id["$service"]="${captured##* }"
  else
    current_ref["$service"]=''
    current_id["$service"]=''
    warn "no running container for $service"
  fi
  say "  $service: ${current_ref[$service]:-<none>}  ->  ${want_ref[$service]}"
done

# The target has to exist before the deployment is touched. A rollback that
# discovers the image is gone *after* rewriting the settings has made things
# worse, not better.
for service in $APP_SERVICES; do
  target="${want_ref[$service]}"
  if ! docker image inspect "$target" >/dev/null 2>&1; then
    is_digest_ref "$target" ||
      die "the $service rollback target is not available locally and cannot be pulled: $target"
    docker pull "$target" >/dev/null || die "could not pull the $service rollback target: $target"
  fi
  if [ -n "${want_id[$service]}" ]; then
    actual_id="$(docker image inspect --format '{{.Id}}' "$target" 2>/dev/null || true)"
    [ "$actual_id" = "${want_id[$service]}" ] ||
      die "the manifest expected image ${want_id[$service]} for $target, local content is $actual_id"
  fi
done

settings_backup="$backup_dir/deployment.env.rollback-$(date -u +%Y%m%dT%H%M%SZ)-$$"
cp -p "$settings" "$settings_backup"
chmod 600 "$settings_backup"

set_setting NEXT_WEB_IMAGE "${want_ref[web]}"
set_setting NEXT_WORKER_IMAGE "${want_ref[worker]}"
set_setting NEXT_EDGE_IMAGE "${want_ref[edge]}"

undo() {
  warn 'the rollback target did not come up; returning to what was running'
  cp -p "$settings_backup" "$settings"
  compose up -d --wait --wait-timeout 240 >/dev/null 2>&1 || {
    warn 'that did not come up either. The stack needs a human.'
    exit 3
  }
  # Landing on the right *reference* is not enough: two builds share a tag and
  # differ in content, and an undo that returned to the wrong one would report
  # success.
  for service in $APP_SERVICES; do
    [ -n "${current_ref[$service]}" ] || continue
    service_runs "$service" "${current_ref[$service]}" "${current_id[$service]}" || {
      warn "  $service did not return to ${current_ref[$service]}. The stack needs a human."
      exit 3
    }
  done
  exit 1
}

say 'starting the rollback target'
compose up -d --wait --wait-timeout 300 >/dev/null || undo
for service in $APP_SERVICES; do
  service_runs "$service" "${want_ref[$service]}" "${want_id[$service]}" || undo
done
readiness_gate || undo

say ''
say 'rolled back:'
for service in $APP_SERVICES; do
  say "  $service -> ${want_ref[$service]}"
done

# --- data recovery, only when asked ------------------------------------------
if [ -n "$restore_file" ]; then
  test -s "$restore_file" || die "the dump is missing or empty: $restore_file"
  gzip -t "$restore_file" || die "the dump is not a complete gzip stream: $restore_file"
  say ''
  warn "About to restore $restore_file over the live database."
  warn 'Every row written since that dump will be gone. This cannot be undone.'
  if [ "$assume_yes" -ne 1 ]; then
    printf 'Type the word restore to continue: '
    read -r answer
    [ "$answer" = 'restore' ] || die 'not confirmed; the database was not touched'
  fi
  # Writers first: a restore racing the application is a restore that ends in a
  # state neither the dump nor the live database ever had.
  say 'stopping the application services'
  # shellcheck disable=SC2086  # deliberate word splitting: a list of services.
  compose stop $APP_SERVICES >/dev/null
  safety="$backup_dir/pre-restore-$(date -u +%Y%m%dT%H%M%SZ)-$$.sql.gz"
  say "taking a safety dump first: $safety"
  "$here/backup.sh" --out "$safety" --no-verify >/dev/null ||
    die 'could not take a safety dump; the database was not touched'
  say 'restoring'
  # The dump carries `--clean --if-exists`, so it drops what it is replacing.
  # shellcheck disable=SC2016  # expanded inside the container, on purpose.
  if ! gzip -dc "$restore_file" | compose exec -T postgres sh -c \
    'exec psql -v ON_ERROR_STOP=1 -q -U "$POSTGRES_USER" -d "$POSTGRES_DB"' >/dev/null; then
    warn "the restore FAILED. The safety dump of the state before it is $safety"
    exit 3
  fi
  compose up -d --wait --wait-timeout 300 >/dev/null || undo
  readiness_gate || undo
  say "database restored from $restore_file (safety dump: $safety)"
else
  say 'Database contents were not changed by this script.'
fi
