'use client';

import {
  ApartmentOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BarChartOutlined,
  BellOutlined,
  BlockOutlined,
  BookOutlined,
  BuildOutlined,
  CalendarOutlined,
  CarOutlined,
  CheckSquareOutlined,
  CloudOutlined,
  ClusterOutlined,
  CodeOutlined,
  CompassOutlined,
  ContainerOutlined,
  ControlOutlined,
  CrownOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeploymentUnitOutlined,
  DollarOutlined,
  EnvironmentOutlined,
  ExperimentOutlined,
  FileImageOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FlagOutlined,
  FolderOutlined,
  FormOutlined,
  FunnelPlotOutlined,
  GiftOutlined,
  GlobalOutlined,
  HomeOutlined,
  IdcardOutlined,
  InboxOutlined,
  KeyOutlined,
  LayoutOutlined,
  LineChartOutlined,
  LinkOutlined,
  MailOutlined,
  MessageOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  NotificationOutlined,
  PayCircleOutlined,
  PhoneOutlined,
  PictureOutlined,
  PieChartOutlined,
  ProfileOutlined,
  QrcodeOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RocketOutlined,
  SafetyOutlined,
  ScheduleOutlined,
  SettingOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SkinOutlined,
  SnippetsOutlined,
  SolutionOutlined,
  SoundOutlined,
  StarOutlined,
  SwapOutlined,
  TableOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TrophyOutlined,
  UnorderedListOutlined,
  UserOutlined,
  WechatOutlined,
} from '@ant-design/icons';
import type { ComponentType, ReactNode } from 'react';

/**
 * Icons a menu file may name. Explicit imports keep the bundle honest — a
 * namespace import would pull all ~850 antd icons into the shell chunk.
 *
 * Need one that isn't here? Add the import and one map entry; it is a two-line
 * change and merges cleanly.
 */
export const MENU_ICONS: Record<string, ComponentType<{ className?: string }>> = {
  ApartmentOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BarChartOutlined,
  BellOutlined,
  BlockOutlined,
  BookOutlined,
  BuildOutlined,
  CalendarOutlined,
  CarOutlined,
  CheckSquareOutlined,
  CloudOutlined,
  ClusterOutlined,
  CodeOutlined,
  CompassOutlined,
  ContainerOutlined,
  ControlOutlined,
  CrownOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeploymentUnitOutlined,
  DollarOutlined,
  EnvironmentOutlined,
  ExperimentOutlined,
  FileImageOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FlagOutlined,
  FolderOutlined,
  FormOutlined,
  FunnelPlotOutlined,
  GiftOutlined,
  GlobalOutlined,
  HomeOutlined,
  IdcardOutlined,
  InboxOutlined,
  KeyOutlined,
  LayoutOutlined,
  LineChartOutlined,
  LinkOutlined,
  MailOutlined,
  MessageOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  NotificationOutlined,
  PayCircleOutlined,
  PhoneOutlined,
  PictureOutlined,
  PieChartOutlined,
  ProfileOutlined,
  QrcodeOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RocketOutlined,
  SafetyOutlined,
  ScheduleOutlined,
  SettingOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SkinOutlined,
  SnippetsOutlined,
  SolutionOutlined,
  SoundOutlined,
  StarOutlined,
  SwapOutlined,
  TableOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TrophyOutlined,
  UnorderedListOutlined,
  UserOutlined,
  WechatOutlined,
};

/** Resolves a menu icon name. Unknown names fall back to a neutral dot. */
export function renderMenuIcon(name: string | undefined): ReactNode {
  if (!name) return undefined;
  const Icon = MENU_ICONS[name] ?? AppstoreOutlined;
  return <Icon />;
}
