/**
 * Aggregates `src/jobs/*.ts` into the gitignored `src/jobs.gen.ts`.
 *
 * Same shape as the contracts aggregation: a domain drops a file in and it is
 * picked up, so parallel streams never edit a shared index.
 *
 * Run: `pnpm --filter @shop/worker gen`
 */
import { glob, writeFile } from 'node:fs/promises';
import path from 'node:path';

const appRoot = path.resolve(import.meta.dirname, '..');
const jobsDir = path.join(appRoot, 'src', 'jobs');

const files: string[] = [];
for await (const entry of glob('*.ts', { cwd: jobsDir })) {
  const name = entry.split(path.sep).join('/');
  if (name.endsWith('.test.ts') || name.startsWith('_')) continue;
  files.push(name);
}
files.sort();

const identifier = (file: string) =>
  `job_${file.replace(/\.ts$/, '').replace(/[^a-zA-Z0-9]/g, '_')}`;

const lines = [
  '// Generated by `pnpm gen` (apps/worker/scripts/gen.ts). Do not edit, do not commit.',
  '/* eslint-disable */',
  "import type { AnyJobDefinition } from './define-job';",
  ...files.map((file) => `import ${identifier(file)} from './jobs/${file.replace(/\.ts$/, '')}';`),
  '',
  '/** Every job this worker can run, in stable filename order. */',
  'export const allJobs: readonly AnyJobDefinition[] = [',
  ...files.map((file) => `  ${identifier(file)} as AnyJobDefinition,`),
  '];',
  '',
];

await writeFile(path.join(appRoot, 'src', 'jobs.gen.ts'), lines.join('\n'), 'utf8');
console.log(`worker: aggregated ${files.length} job file(s)`);
