import type { ResponseOf } from '@shop/api-client';

export const invoiceTitleFixture: ResponseOf<'user.invoiceTitleDetail'> = {
  id: '7001',
  headerType: 'company',
  invoiceType: 'plain',
  name: '深圳某某科技有限公司',
  dutyNumber: '91440300MA5XXXXX1B',
  drawerPhone: null,
  email: 'finance@example.com',
  registeredTel: null,
  registeredAddress: null,
  bankName: null,
  bankAccount: null,
  isDefault: true,
  createdAt: '2026-09-01T10:00:00+08:00',
  updatedAt: '2026-09-01T10:00:00+08:00',
};

export const personalTitleFixture: ResponseOf<'user.invoiceTitleDetail'> = {
  ...invoiceTitleFixture,
  id: '7002',
  headerType: 'personal',
  name: '李四',
  dutyNumber: null,
  email: null,
  isDefault: false,
};

export const orderInvoiceFixture: ResponseOf<'order.myInvoiceDetail'> = {
  id: '3001',
  orderId: '9001',
  orderNo: '202609201000000010123456',
  userId: '7',
  status: 'requested',
  headerType: 'company',
  invoiceType: 'plain',
  name: '深圳某某科技有限公司',
  dutyNumber: '91440300MA5XXXXX1B',
  drawerPhone: null,
  email: 'finance@example.com',
  registeredTel: null,
  registeredAddress: null,
  bankName: null,
  bankAccount: null,
  amount: '118.00',
  invoiceNumber: null,
  remark: null,
  orderSummary: {
    productName: '纯棉毛巾',
    productImageUrl: '/uploads/p/11.jpg',
    specText: '白色',
    quantity: 2,
    lineCount: 2,
    totalQuantity: 3,
  },
  issuedAt: null,
  createdAt: '2026-09-21T10:00:00+08:00',
};

export const paidOrderFixture: ResponseOf<'order.detail'> = {
  id: '9001',
  orderNo: '202609201000000010123456',
  kind: 'normal',
  status: 'paid',
  fulfillmentStatus: 'unfulfilled',
  refundStatus: 'none',
  totalQuantity: 2,
  itemsAmount: '120.00',
  freightAmount: '8.00',
  couponDiscount: '10.00',
  payableAmount: '118.00',
  paidAmount: '118.00',
  payExpiresAt: null,
  createdAt: '2026-09-20T10:00:00+08:00',
  items: [
    {
      id: '8001',
      itemKey: 'sku-21',
      productId: '11',
      skuId: '21',
      productName: '纯棉毛巾',
      productImageUrl: '/uploads/p/11.jpg',
      productKind: 'physical',
      specText: '白色',
      skuImageUrl: null,
      unitName: '条',
      quantity: 2,
      unitPrice: '60.00',
      originalUnitPrice: null,
      discountAmount: '10.00',
      totalAmount: '110.00',
      refundedQuantity: 0,
      shippedQuantity: 0,
      adjustments: [],
    },
  ],
  receiver: {
    addressId: '31',
    name: '李四',
    phone: '13800138000',
    province: '广东省',
    city: '深圳市',
    district: '南山区',
    detail: '科技园 1 号',
    postCode: null,
  },
  buyerRemark: null,
  customForm: null,
  userCouponId: null,
  paidAt: '2026-09-20T10:01:00+08:00',
  shippedAt: null,
  receivedAt: null,
  completedAt: null,
  cancelledAt: null,
  cancelReason: null,
};
