/**
 * Aggregates `@shop/core`'s two side-effect buckets, so a domain joins the
 * system by adding files in its own directory and nothing shared is edited.
 *
 *  - `src/config-groups.gen.ts` imports every `src/<domain>/*.config.ts`, which
 *    is what fills `defineConfigGroup`'s registry: a group nobody imported is
 *    simply not on the settings index, with no error anywhere (CR-3-f1).
 *  - `src/domains.gen.ts` imports every `src/<domain>/index.ts` and calls every
 *    exported `register<Name>Domain()` it finds, which is what installs the
 *    ports, the order state machine and the effect handlers. Without it a Next
 *    route only loads the domain it serves, so a checkout ran on B1's fallback
 *    adapter and `refund.execute` was parked as `unknown` (CR-8-c).
 *
 * Both are gitignored (`*.gen.ts`) and both are pure import order — the
 * generated files carry no logic, so a domain can never be half-registered.
 *
 * Run: `pnpm --filter @shop/core gen`
 */
import { glob, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const srcDir = path.resolve(import.meta.dirname, '..', 'src');

/** `kernel` is the platform, not a domain: it registers nothing and is imported everywhere. */
const NOT_A_DOMAIN = new Set(['kernel']);

/** The one shape a registration function may take, per CONVENTIONS. */
const REGISTER_FN = /^export function (register[A-Z]\w*Domain)\s*\(/gm;

const posix = (entry: string): string => entry.split(path.sep).join('/');

// ---------------------------------------------------------------------------
// config-groups.gen.ts
// ---------------------------------------------------------------------------

/** `group: 'storage'` inside a `defineConfigGroup({ … })` call. */
const GROUP_NAME = /\bgroup:\s*'([a-z][a-z0-9-]{1,31})'/g;

const configFiles: string[] = [];
const declaredBy = new Map<string, string>();
for await (const entry of glob('*/*.config.ts', { cwd: srcDir })) {
  const name = posix(entry);
  if (name.endsWith('.test.ts')) continue;
  configFiles.push(name);

  // `defineConfigGroup` throws on a duplicate, but only says which name; here
  // both files are in hand, which is the half an operator needs.
  const source = await readFile(path.join(srcDir, entry), 'utf8');
  for (const [, group] of source.matchAll(GROUP_NAME)) {
    const first = declaredBy.get(group!);
    if (first !== undefined && first !== name) {
      throw new Error(`core: config group "${group}" 被两个文件声明：src/${first} 与 src/${name}`);
    }
    declaredBy.set(group!, name);
  }
}
configFiles.sort();

await writeFile(
  path.join(srcDir, 'config-groups.gen.ts'),
  [
    '// Generated by `pnpm gen` (packages/core/scripts/gen-config-groups.ts).',
    '// Do not edit, do not commit.',
    '/* eslint-disable */',
    ...configFiles.map((file) => `import './${file.replace(/\.ts$/, '')}';`),
    '',
    `/** ${configFiles.length} config group file(s), imported for their registration side effect. */`,
    'export const CONFIG_GROUP_FILES = [',
    ...configFiles.map((file) => `  '${file}',`),
    '] as const;',
    '',
  ].join('\n'),
  'utf8',
);

// ---------------------------------------------------------------------------
// domains.gen.ts
// ---------------------------------------------------------------------------

const domains: { name: string; registrars: string[] }[] = [];
for await (const entry of glob('*/index.ts', { cwd: srcDir })) {
  const name = posix(entry).split('/')[0]!;
  if (NOT_A_DOMAIN.has(name)) continue;
  // Scanned statically rather than by importing and reflecting: the generated
  // file has to be readable, and a build must not run domain code to be built.
  const source = await readFile(path.join(srcDir, entry), 'utf8');
  const registrars = [...source.matchAll(REGISTER_FN)].map((match) => match[1]!).sort();
  domains.push({ name, registrars });
}
domains.sort((a, b) => a.name.localeCompare(b.name));

const registrarCount = domains.reduce((n, d) => n + d.registrars.length, 0);

await writeFile(
  path.join(srcDir, 'domains.gen.ts'),
  [
    '// Generated by `pnpm gen` (packages/core/scripts/gen-config-groups.ts).',
    '// Do not edit, do not commit.',
    '/* eslint-disable */',
    // Bare side-effect imports first: a namespace import that is never read is
    // elided by esbuild / tsx (the ETL CLI found this — J), which would drop
    // every domain that registers on import and has no explicit registrar.
    ...domains.map(({ name }) => `import './${name}/index';`),
    ...domains
      .filter(({ registrars }) => registrars.length > 0)
      .map(({ name, registrars }) => `import { ${registrars.join(', ')} } from './${name}/index';`),
    '',
    '/**',
    ' * Installs every domain: the import registers what a domain registers as a',
    ' * module side effect, and the calls below cover the domains that publish an',
    ' * explicit `register<Name>Domain()` instead. Order does not matter — every',
    ' * registration is a map write or a slot assignment, and no domain reads',
    " * another's port while registering — and every registrar is idempotent, so",
    ' * calling this twice is harmless.',
    ' */',
    'export function registerAllDomains(): void {',
    ...domains.flatMap(({ registrars }) => registrars.map((fn) => `  ${fn}();`)),
    '}',
    '',
    'registerAllDomains();',
    '',
    `/** ${domains.length} domain(s), ${registrarCount} explicit registrar(s). */`,
    'export const DOMAIN_NAMES = [',
    ...domains.map(({ name }) => `  '${name}',`),
    '] as const;',
    '',
  ].join('\n'),
  'utf8',
);

console.log(
  `core: aggregated ${configFiles.length} config group file(s), ` +
    `${domains.length} domain(s) with ${registrarCount} registrar(s)`,
);
