/**
 * Writes `src/storefront-routes.gen.ts`: the storefront route catalogue
 * (`@shop/contracts/system/storefront-routes`, docs/mini/pages.md §3) as the
 * mini-program needs it, a plain object with no zod.
 *
 *   storefrontRoutes[key] = { path, params: string[], tab, share }
 *
 * `params` lists the names a key takes (for `order`, both `id` and
 * `outTradeNo`, of which a link carries one). The param *types* come from the
 * contracts through `import type` and are erased from every bundle.
 *
 * Run: `pnpm --filter @shop/api-client gen` (or `pnpm gen` from the root).
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { storefrontRouteDef, storefrontRouteKeys } from '@shop/contracts/system/storefront-routes';
import { z } from 'zod';

const pkgRoot = path.resolve(import.meta.dirname, '..');
const outFile = path.join(pkgRoot, 'src/storefront-routes.gen.ts');
const SOURCE = '@shop/contracts/system/storefront-routes';

const HEADER = `// Generated by \`pnpm gen\` (packages/api-client/scripts/gen-storefront-routes.ts). Do not edit, do not commit.\n/* eslint-disable */\n`;

/** The param names of an object schema, or of every branch of a union of them. */
function paramNames(schema: z.ZodType, key: string): string[] {
  if (schema instanceof z.ZodObject) return Object.keys(schema.shape);
  if (schema instanceof z.ZodUnion) {
    const names = (schema.options as z.ZodType[]).flatMap((option) => paramNames(option, key));
    return [...new Set(names)];
  }
  throw new Error(`${key}: params must be an object schema or a union of them`);
}

const q = (value: string): string => JSON.stringify(value);

async function main(): Promise<void> {
  const lines: string[] = [HEADER];
  lines.push(`import type { StorefrontRoute, StorefrontRouteParams } from ${q(SOURCE)};`);
  lines.push('');
  lines.push(`export type { StorefrontRoute, StorefrontRouteParams };`);
  lines.push('');
  lines.push(`/** What the share menu offers on a page. */`);
  lines.push(`export type StorefrontShare = 'none' | 'friend' | 'friend+timeline';`);
  lines.push('');
  lines.push(
    `/** A catalogue entry: page path (no leading \`/\`), param names, tabBar page, share menu. */`,
  );
  lines.push(`export interface StorefrontRouteEntry {`);
  lines.push(`  readonly path: string;`);
  lines.push(`  readonly params: readonly string[];`);
  lines.push(`  readonly tab: boolean;`);
  lines.push(`  readonly share: StorefrontShare;`);
  lines.push(`}`);
  lines.push('');
  lines.push(
    `/** The storefront route catalogue, key -> page. Plain data, no zod. Keys are append-only. */`,
  );
  lines.push(`export const storefrontRoutes = {`);
  for (const key of storefrontRouteKeys) {
    const def = storefrontRouteDef(key);
    const params = paramNames(def.params, key).map(q).join(', ');
    lines.push(
      `  ${key}: { path: ${q(def.path)}, params: [${params}], tab: ${def.tab === true}, share: ${q(def.share)} },`,
    );
  }
  lines.push(`} as const satisfies Record<string, StorefrontRouteEntry>;`);
  lines.push('');
  lines.push(`export type StorefrontRouteKey = keyof typeof storefrontRoutes;`);
  lines.push('');

  await writeFile(outFile, lines.join('\n'), 'utf8');
  console.log(`api-client: ${storefrontRouteKeys.length} storefront page route(s)`);
}

await main();
