/**
 * Writes `src/routes.gen.ts`: the storefront slice of the contracts, in the
 * two forms a client needs and nothing more.
 *
 *   - `storefrontRouteList`, a plain runtime table `{ id, method, path, auth }`
 *     per route. No zod, no examples, no admin path: this is what ends
 *     up in the mini-program bundle.
 *   - interfaces that map each route id to `typeof <contract>` (and to the
 *     parts it declares and the error codes it lists) through `import type`
 *     only, so the schemas type every call and are erased at build time.
 *
 * It loads the contracts in Node, at build time, which is the only place
 * `allRoutes` (every contract, every example, zod) may be loaded.
 *
 * Run: `pnpm --filter @shop/api-client gen` (or `pnpm gen` from the root, which
 * runs `@shop/contracts`' own gen first).
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { AnyRouteDef, AuthMode } from '@shop/contracts/conventions';
import { allRoutes, routeSources } from '@shop/contracts/routes';

const pkgRoot = path.resolve(import.meta.dirname, '..');
const outFile = path.join(pkgRoot, 'src/routes.gen.ts');

const HEADER = `// Generated by \`pnpm gen\` (packages/api-client/scripts/gen.ts). Do not edit, do not commit.\n/* eslint-disable */\n`;

/** The auth modes a shopper's client calls. `admin` and `webhook` are not the storefront's. */
const CLIENT_AUTH: ReadonlySet<AuthMode> = new Set(['public', 'user', 'user-optional']);

function isClientRoute(route: AnyRouteDef): boolean {
  return route.path.startsWith('/api/v1/') && CLIENT_AUTH.has(route.auth);
}

interface Entry {
  route: AnyRouteDef;
  /** `@shop/contracts/<file without .ts>`, the specifier the type import uses. */
  specifier: string;
  exportName: string;
  alias: string;
}

async function locate(route: AnyRouteDef): Promise<Entry> {
  const file = routeSources[route.id];
  if (!file) throw new Error(`${route.id}: no source file in routeSources`);
  const specifier = `@shop/contracts/${file.replace(/\.ts$/, '')}`;
  const mod = (await import(specifier)) as Record<string, unknown>;
  const exportName = Object.keys(mod).find((name) => mod[name] === route);
  if (!exportName) throw new Error(`${route.id}: not a named export of ${specifier}`);
  return { route, specifier, exportName, alias: route.id.replace(/[^A-Za-z0-9]/g, '_') };
}

const q = (value: string): string => JSON.stringify(value);

function union(values: readonly string[]): string {
  return values.length === 0 ? 'never' : [...new Set(values)].sort().map(q).join(' | ');
}

async function main(): Promise<void> {
  const selected = allRoutes.filter(isClientRoute).sort((a, b) => a.id.localeCompare(b.id));
  const entries = await Promise.all(selected.map(locate));

  const ids = new Set<string>();
  for (const { route } of entries) {
    if (ids.has(route.id)) throw new Error(`duplicate route id ${route.id}`);
    ids.add(route.id);
  }

  const lines: string[] = [HEADER];

  // -- type-only imports, one statement per contract file --------------------
  const byFile = new Map<string, Entry[]>();
  for (const entry of entries) {
    const list = byFile.get(entry.specifier) ?? [];
    list.push(entry);
    byFile.set(entry.specifier, list);
  }
  for (const specifier of [...byFile.keys()].sort()) {
    const names = (byFile.get(specifier) ?? []).map((e) => `${e.exportName} as ${e.alias}`);
    lines.push(`import type { ${names.join(', ')} } from ${q(specifier)};`);
  }
  lines.push('');

  // -- the runtime table -----------------------------------------------------
  lines.push(
    `/** Every storefront route a shopper's client calls: id, method, path, auth. Plain data, no zod. */`,
  );
  lines.push(`export const storefrontRouteList = [`);
  for (const { route } of entries) {
    lines.push(
      `  { id: ${q(route.id)}, method: ${q(route.method)}, path: ${q(route.path)}, auth: ${q(route.auth)} },`,
    );
  }
  lines.push(`] as const;`);
  lines.push('');

  // -- type maps ---------------------------------------------------------------
  lines.push(`/** Route id -> its contract. Types only: erased from every bundle. */`);
  lines.push(`export interface StorefrontContracts {`);
  for (const { route, alias } of entries) lines.push(`  ${q(route.id)}: typeof ${alias};`);
  lines.push(`}`);
  lines.push('');

  lines.push(
    `/** Route id -> the request parts its contract declares (a route that omits one takes none). */`,
  );
  lines.push(`export interface StorefrontRouteParts {`);
  for (const { route } of entries) {
    const parts = (['params', 'query', 'body'] as const).filter(
      (part) => route[part] !== undefined,
    );
    lines.push(`  ${q(route.id)}: ${union(parts)};`);
  }
  lines.push(`}`);
  lines.push('');

  lines.push(`/** Route id -> the error codes its contract lists in \`errors\`. */`);
  lines.push(`export interface StorefrontDeclaredErrors {`);
  for (const { route } of entries) lines.push(`  ${q(route.id)}: ${union(route.errors ?? [])};`);
  lines.push(`}`);
  lines.push('');

  await writeFile(outFile, lines.join('\n'), 'utf8');
  const excluded = allRoutes.filter((r) => r.path.startsWith('/api/v1/') && !isClientRoute(r));
  console.log(
    `api-client: ${entries.length} storefront route(s) from ${byFile.size} contract file(s); ${excluded.length} webhook route(s) left out`,
  );
}

await main();
