/**
 * Aggregates the per-domain contract files into two gitignored bucket files.
 *
 *   src/<domain>/**\/*.contract.ts  ->  src/routes.gen.ts   (`allRoutes`)
 *   src/<domain>/errors.ts          ->  src/errors.gen.ts   (`errorRegistry`)
 *
 * Domains own their own files and never edit a shared index, so ten streams can
 * add routes in parallel without ever touching the same line. Directories whose
 * name starts with `_` are conventions/helpers, not domains.
 *
 * Run: `pnpm --filter @shop/contracts gen`
 */
import { glob } from 'node:fs/promises';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';

const pkgRoot = path.resolve(import.meta.dirname, '..');
const srcDir = path.join(pkgRoot, 'src');

const HEADER = `// Generated by \`pnpm gen\` (packages/contracts/scripts/gen.ts). Do not edit, do not commit.\n/* eslint-disable */\n`;

async function collect(pattern: string): Promise<string[]> {
  const out: string[] = [];
  for await (const entry of glob(pattern, { cwd: srcDir })) {
    const posix = entry.split(path.sep).join('/');
    if (posix.startsWith('_')) continue; // `_conventions/*`
    out.push(posix);
  }
  return out.sort();
}

/** `health/health.contract.ts` -> `health_health_contract` */
function identifier(relative: string): string {
  return relative.replace(/\.ts$/, '').replace(/[^a-zA-Z0-9]/g, '_');
}

async function genRoutes(): Promise<number> {
  const files = await collect('*/**/*.contract.ts');
  const lines: string[] = [HEADER, `import type { AnyRouteDef } from './_conventions/route';`];
  for (const file of files)
    lines.push(`import * as ${identifier(file)} from './${file.replace(/\.ts$/, '')}';`);
  lines.push('');
  lines.push(`const modules: Record<string, Record<string, unknown>> = {`);
  for (const file of files) lines.push(`  ${JSON.stringify(file)}: ${identifier(file)},`);
  lines.push(`};`);
  lines.push('');
  lines.push(`function isRoute(value: unknown): value is AnyRouteDef {`);
  lines.push(`  if (typeof value !== 'object' || value === null) return false;`);
  lines.push(`  const v = value as Record<string, unknown>;`);
  lines.push(
    `  return typeof v.id === 'string' && typeof v.method === 'string' && typeof v.path === 'string' && Array.isArray(v.examples);`,
  );
  lines.push(`}`);
  lines.push('');
  lines.push(`/** Every route the system exposes, in stable (file, export) order. */`);
  lines.push(`export const allRoutes: readonly AnyRouteDef[] = Object.entries(modules).flatMap(`);
  lines.push(`  ([, mod]) => Object.values(mod).filter(isRoute),`);
  lines.push(`);`);
  lines.push('');
  lines.push(`/** Source file of each route id, for error messages in the guards. */`);
  lines.push(`export const routeSources: Readonly<Record<string, string>> = Object.fromEntries(`);
  lines.push(
    `  Object.entries(modules).flatMap(([file, mod]) => Object.values(mod).filter(isRoute).map((r) => [r.id, file] as const)),`,
  );
  lines.push(`);`);
  lines.push('');
  await writeFile(path.join(srcDir, 'routes.gen.ts'), lines.join('\n'), 'utf8');
  return files.length;
}

async function genErrors(): Promise<number> {
  const files = await collect('*/errors.ts');
  const lines: string[] = [
    HEADER,
    `import type { ErrorSpec } from './_conventions/errors';`,
    `import { commonErrors } from './_conventions/errors';`,
  ];
  for (const file of files)
    lines.push(`import * as ${identifier(file)} from './${file.replace(/\.ts$/, '')}';`);
  lines.push('');
  lines.push(`function isSpec(value: unknown): value is ErrorSpec {`);
  lines.push(`  if (typeof value !== 'object' || value === null) return false;`);
  lines.push(`  const v = value as Record<string, unknown>;`);
  lines.push(`  return typeof v.status === 'number' && typeof v.message === 'string';`);
  lines.push(`}`);
  lines.push('');
  lines.push(`function flatten(mod: Record<string, unknown>): Record<string, ErrorSpec> {`);
  lines.push(`  const out: Record<string, ErrorSpec> = {};`);
  lines.push(`  for (const registry of Object.values(mod)) {`);
  lines.push(`    if (typeof registry !== 'object' || registry === null) continue;`);
  lines.push(
    `    for (const [code, spec] of Object.entries(registry as Record<string, unknown>)) if (isSpec(spec)) out[code] = spec;`,
  );
  lines.push(`  }`);
  lines.push(`  return out;`);
  lines.push(`}`);
  lines.push('');
  lines.push(
    `/** Every error code in the system, keyed by code. \`handle()\` resolves DomainError through this. */`,
  );
  lines.push(`export const errorRegistry: Readonly<Record<string, ErrorSpec>> = {`);
  lines.push(`  ...commonErrors,`);
  for (const file of files) lines.push(`  ...flatten(${identifier(file)}),`);
  lines.push(`};`);
  lines.push('');
  await writeFile(path.join(srcDir, 'errors.gen.ts'), lines.join('\n'), 'utf8');
  return files.length;
}

const [routes, errors] = await Promise.all([genRoutes(), genErrors()]);
console.log(`contracts: aggregated ${routes} contract file(s), ${errors} error file(s)`);
