<?php
declare(strict_types=1);

namespace Tests\Regression\Cases;

use app\services\order\StoreOrderRefundServices;
use app\services\order\StoreOrderServices;
use Tests\Regression\Support\BusinessSnapshot;
use Tests\Regression\Support\FixtureFactory;
use Tests\Regression\Support\RegressionTestCase;
use Tests\Regression\Support\StatefulGateway;
use Tests\Regression\Support\WorkerProcess;
use think\facade\Db;

/**
 * Refund freeze, execution and completion consistency.
 *
 * A refund request freezes its refund number, amount and full payment context;
 * execution re-checks the after-sale state and the frozen request under the row
 * lock; gateway intent commits before the network call; and the local
 * completion is generated by the service, not by the caller.
 */
final class RefundConcurrencyTest extends RegressionTestCase
{
    private StatefulGateway $gateway;

    private string $token = '';

    protected function setUp(): void
    {
        parent::setUp();
        $this->gateway = StatefulGateway::fresh();
        $gateway = $this->gateway;
        $this->bindClass(\crmeb\services\pay\Pay::class, static function () use ($gateway) {
            return $gateway;
        });
        $this->token = substr(bin2hex(random_bytes(5)), 0, 10);
        $token = $this->token;
        $this->registerCleanup(static function () use ($token): void {
            $rows = Db::name('store_order_refund')->whereLike('order_id', $token . '%')->column('id');
            if ($rows) {
                Db::name('store_order_refund')->whereIn('id', $rows)->delete();
            }
        });
    }

    public function testUserCancellationRejectsGatewayStatesWithoutChangingRows(): void
    {
        [$id, $orderId] = $this->paidWechatOrder('cancel', '10.00');
        $service = app()->make(StoreOrderRefundServices::class);
        foreach ([1, 2, 3] as $state) {
            Db::name('store_order_refund')->where('id', $id)->update(['refund_state' => $state]);
            $before = BusinessSnapshot::refund($id);
            $carts = Db::name('store_order_cart_info')->where('oid', $orderId)->select()->toArray();
            try {
                $service->cancelUserRefund($before['order_id'], (int)$before['uid']);
                self::fail('gateway state must prevent cancellation');
            } catch (\crmeb\exceptions\ApiException $e) {
                self::assertStringContainsString('不能取消', $e->getMessage());
            }
            self::assertSame($before, BusinessSnapshot::refund($id));
            self::assertSame($carts, Db::name('store_order_cart_info')->where('oid', $orderId)->select()->toArray());
        }
        Db::name('store_order_refund')->where('id', $id)->update(['refund_state' => 0]);
        try {
            $service->cancelUserRefund($before['order_id'], (int)$before['uid'] + 1);
            self::fail('another user must not cancel');
        } catch (\crmeb\exceptions\ApiException $e) {
            self::assertStringContainsString('不存在', $e->getMessage());
        }
        $service->cancelUserRefund($before['order_id'], (int)$before['uid']);
        self::assertSame(1, (int)BusinessSnapshot::refund($id)['is_cancel']);
        self::assertSame(0, (int)Db::name('store_order_cart_info')->where('oid', $orderId)->sum('refund_num'));
    }

    public function testCancellationRollsBackWhenBookkeepingFails(): void
    {
        [$id, $orderId] = $this->paidWechatOrder('rollback', '10.00');
        $before = BusinessSnapshot::refund($id);
        $carts = Db::name('store_order_cart_info')->where('oid', $orderId)->select()->toArray();
        $status = $this->getMockBuilder(\app\services\order\StoreOrderStatusServices::class)
            ->disableOriginalConstructor()->addMethods(['save'])->getMock();
        $status->expects(self::once())->method('save')->willThrowException(new \RuntimeException('bookkeeping failure'));
        $this->replace(\app\services\order\StoreOrderStatusServices::class, $status);
        try {
            app()->make(StoreOrderRefundServices::class)->cancelUserRefund($before['order_id'], (int)$before['uid']);
            self::fail('bookkeeping must fail');
        } catch (\RuntimeException $e) {
            self::assertSame('bookkeeping failure', $e->getMessage());
        }
        self::assertSame($before, BusinessSnapshot::refund($id));
        self::assertSame($carts, Db::name('store_order_cart_info')->where('oid', $orderId)->select()->toArray());
    }

    /**
     * REFUND-007: a retry that carries a different amount is refused outright
     * instead of silently reusing the frozen amount.
     */
    public function testARetryWithADifferentAmountIsRefused(): void
    {
        [$refundId, $orderId] = $this->paidWechatOrder('amount', '10.00');

        /** @var StoreOrderRefundServices $refunds */
        $refunds = app()->make(StoreOrderRefundServices::class);
        $first = $refunds->agreeRefund($refundId, ['refund_price' => '10.00', 'pay_price' => '10.00'], []);
        self::assertTrue($first, 'the first refund succeeds');
        self::assertSame(1, $this->gateway->refundRowCount($this->refundGatewayKey($orderId)), 'the gateway refunded once');

        // A second after-sale row for the same payment attempts a different
        // amount on top: it must be refused, not silently accepted.
        $second = $this->newAfterSale($orderId, '6.00');
        try {
            $refunds->agreeRefund($second, ['refund_price' => '6.00', 'pay_price' => '10.00'], []);
        } catch (\Throwable $e) {
            self::assertMatchesRegularExpression('/冻结|累计退款/', $e->getMessage(), 'a different amount is refused');
        }
        $row = BusinessSnapshot::refund($second);
        self::assertNotSame(6, (int)$row['refund_type'], 'the second refund must not complete');
    }

    /**
     * REFUND-007: the executed refund re-checks the after-sale state inside the
     * transaction. A cancelled after-sale refuses, and a completed one refuses
     * with no additional gateway call.
     */
    public function testExecutionRefusesACancelledOrCompletedAfterSale(): void
    {
        [$refundId, $orderId] = $this->paidWechatOrder('state', '10.00');
        /** @var StoreOrderRefundServices $refunds */
        $refunds = app()->make(StoreOrderRefundServices::class);

        // Cancelled before execution.
        Db::name('store_order_refund')->where('id', $refundId)->update(['is_cancel' => 1]);
        try {
            $refunds->agreeRefund($refundId, ['refund_price' => '10.00', 'pay_price' => '10.00'], []);
            self::fail('a cancelled after-sale must refuse the refund');
        } catch (\Throwable $e) {
            self::assertStringContainsString('已取消', $e->getMessage());
        }
        self::assertSame(0, $this->gateway->refundRowCount($this->refundGatewayKey($orderId)), 'nothing reached the gateway');

        // Completed after-sale: a retry is refused and adds no gateway call.
        Db::name('store_order_refund')->where('id', $refundId)->update(['is_cancel' => 0, 'refund_type' => 6, 'refunded_price' => '10.00']);
        try {
            $refunds->agreeRefund($refundId, ['refund_price' => '10.00', 'pay_price' => '10.00'], []);
            self::fail('a completed after-sale must refuse the refund');
        } catch (\Throwable $e) {
            self::assertStringContainsString('已完成', $e->getMessage());
        }
        self::assertSame(0, $this->gateway->refundRowCount($this->refundGatewayKey($orderId)), 'a completed retry adds no gateway refund');
    }

    /**
     * REFUND-007: the local completion is generated by the service from the
     * frozen request. The caller's stale/absent refunded_price does not matter.
     */
    public function testTheServiceGeneratesTheLocalCompletionFromTheFrozenRequest(): void
    {
        [$refundId, $orderId] = $this->paidWechatOrder('completion', '10.00');
        /** @var StoreOrderRefundServices $refunds */
        $refunds = app()->make(StoreOrderRefundServices::class);

        // Deliberately pass a stale completion the way an old controller would.
        $refunds->agreeRefund($refundId, ['refund_price' => '4.00', 'pay_price' => '10.00'], ['refund_type' => 6, 'refunded_price' => '999.00', 'refunded_time' => 1]);

        $row = BusinessSnapshot::refund($refundId);
        self::assertSame(6, (int)$row['refund_type'], 'the after-sale is completed by the service');
        self::assertSame('4.00', (string)$row['refunded_price'], 'the completed amount comes from the service, not the caller');
        self::assertNotSame(1, (int)$row['refunded_time'], 'the completion time comes from the service');
        self::assertSame(StoreOrderRefundServices::REFUND_STATE_SUCCESS, (int)$row['refund_state'], 'the refund state records success');
        self::assertSame('4.00', (string)$row['refund_request'] ? (string)(json_decode($row['refund_request'], true)['refund_price'] ?? '') : '', 'the frozen amount matches the request');
    }

    /**
     * REFUND-007: two processes calling the full agreeRefund() for one
     * after-sale freeze one refund number and one amount, and the gateway pays
     * out once.
     */
    public function testTwoProcessesAgreeingOneRefundPayOutOnce(): void
    {
        [$refundId, $orderId] = $this->paidWechatOrder('race', '10.00');

        $results = WorkerProcess::run([
            'a' => sprintf('refund-agree %d 10.00', $refundId),
            'b' => sprintf('refund-agree %d 10.00', $refundId),
        ], ['CRMEB_TEST_GATEWAY' => '1']);

        $succeeded = array_filter($results, static function (array $r): bool {
            return $r['ok'];
        });
        self::assertGreaterThanOrEqual(1, count($succeeded), 'at least one process completes the refund');
        foreach ($results as $name => $result) {
            if (!$result['ok']) {
                self::assertMatchesRegularExpression('/已完成|已有网关请求/', $result['error'], $name . ' lost the race cleanly: ' . $result['error']);
            }
        }

        $row = BusinessSnapshot::refund($refundId);
        self::assertSame(6, (int)$row['refund_type']);
        self::assertSame(1, $this->gateway->refundRowCount($this->refundGatewayKey($orderId)), 'the gateway holds exactly one refund row');
        $orders = Db::name('store_order_refund')->where('store_order_id', $orderId)->where('refund_type', 6)->count();
        self::assertSame(1, (int)$orders, 'one completed after-sale');
    }

    /**
     * REFUND-007: the gateway accepted the refund but the local transaction
     * failed. The state stays processing, and a retry first queries the frozen
     * number and completes the local write without refunding again.
     */
    public function testGatewayAcceptedWithLocalFailureIsRecoveredByQuery(): void
    {
        [$refundId, $orderId] = $this->paidWechatOrder('recover', '10.00');
        $gatewayKey = $this->refundGatewayKey($orderId);
        /** @var StoreOrderRefundServices $refunds */
        $refunds = app()->make(StoreOrderRefundServices::class);

        // First attempt: the gateway accepts, then the local write is aborted.
        Db::name('store_order_refund')->where('id', $refundId)->update([
            'out_refund_no' => 'RR-' . $refundId,
            'refund_state' => StoreOrderRefundServices::REFUND_STATE_PROCESSING,
            'refund_request' => json_encode([
                'refund_price' => '10.00',
                'context' => ['driver' => 'wechat_pay', 'order_id' => $this->refundGatewayKey($orderId), 'trade_no' => $this->gateway->gatewayOrder($gatewayKey)['trade_no'] ?? ''],
            ]),
        ]);
        $this->gateway->seedRefund('RR-' . $refundId, $gatewayKey, '10.00', 'success');

        $before = BusinessSnapshot::refund($refundId);
        try {
            $refunds->cancelUserRefund($before['order_id'], (int)$before['uid']);
            self::fail('submitted gateway refund must not be cancelled');
        } catch (\crmeb\exceptions\ApiException $e) {
            self::assertStringContainsString('不能取消', $e->getMessage());
        }
        $result = $refunds->retryUnknownRefund($refundId, 'operator-recover');
        self::assertSame('success', $result['status']);
        $row = BusinessSnapshot::refund($refundId);
        self::assertSame(6, (int)$row['refund_type'], 'the local completion is filled in');
        self::assertSame('10.00', (string)$row['refunded_price']);
        self::assertSame(StoreOrderRefundServices::REFUND_STATE_SUCCESS, (int)$row['refund_state']);
        self::assertSame(1, $this->gateway->refundRowCount($gatewayKey), 'the recovery did not refund again');
    }

    /**
     * REFUND-007: an unknown gateway answer keeps the after-sale in the unknown
     * state and the retry refuses to guess.
     */
    public function testAnUnknownGatewayRefundKeepsTheUnknownState(): void
    {
        [$refundId, $orderId] = $this->paidWechatOrder('unknown', '10.00');
        /** @var StoreOrderRefundServices $refunds */
        $refunds = app()->make(StoreOrderRefundServices::class);
        Db::name('store_order_refund')->where('id', $refundId)->update([
            'out_refund_no' => 'RU-' . $refundId,
            'refund_state' => StoreOrderRefundServices::REFUND_STATE_PROCESSING,
            'refund_request' => json_encode([
                'refund_price' => '10.00',
                'context' => ['driver' => 'wechat_pay', 'order_id' => $this->refundGatewayKey($orderId)],
            ]),
        ]);

        try {
            $refunds->retryUnknownRefund($refundId, 'operator-unknown');
            self::fail('an unconfirmed refund must not be completed');
        } catch (\Throwable $e) {
            self::assertStringContainsString('人工核实', $e->getMessage());
        }
        $row = BusinessSnapshot::refund($refundId);
        self::assertSame(StoreOrderRefundServices::REFUND_STATE_UNKNOWN, (int)$row['refund_state'], 'the unknown state is preserved');
        self::assertSame('RU-' . $refundId, (string)$row['out_refund_no'], 'the frozen number is untouched');
    }

    /**
     * REFUND-007: the cumulative refunds of one original payment never exceed
     * what was paid, and a partial refund followed by a second one is allowed
     * up to the limit only.
     */
    public function testCumulativeRefundsCannotExceedThePaidAmount(): void
    {
        [$refundId, $orderId] = $this->paidWechatOrder('cumulative', '10.00');
        /** @var StoreOrderRefundServices $refunds */
        $refunds = app()->make(StoreOrderRefundServices::class);
        // First partial refund of 6.00 completes.
        self::assertTrue($refunds->agreeRefund($refundId, ['refund_price' => '6.00', 'pay_price' => '10.00'], []));

        // A second after-sale for the same payment asks for 6.00 more: over the limit.
        $second = $this->newAfterSale($orderId, '6.00');
        try {
            $refunds->agreeRefund($second, ['refund_price' => '6.00', 'pay_price' => '10.00'], []);
            self::fail('the cumulative refund limit must be enforced');
        } catch (\Throwable $e) {
            self::assertMatchesRegularExpression('/累计退款|冻结/', $e->getMessage());
        }
        // A third asking for the remaining 4.00 is within the limit and proceeds.
        $third = $this->newAfterSale($orderId, '4.00');
        self::assertTrue($refunds->agreeRefund($third, ['refund_price' => '4.00', 'pay_price' => '10.00'], []), 'the remaining amount can be refunded');
        self::assertSame(2, $this->gateway->refundRowCount($this->refundGatewayKey($orderId)), 'two refunds were really paid out');
    }

    /**
     * Build a paid WeChat order with one after-sale row in an agreeable state.
     *
     * @return array{0:int,1:int} after-sale id and order id
     */
    private function paidWechatOrder(string $label, string $amount): array
    {
        $fixtures = new FixtureFactory($this, $this->getName());
        $user = $fixtures->createUser();
        $product = $fixtures->createProduct([], ['stock' => 5]);
        $orderId = $this->token . '-' . $label;
        $order = $fixtures->createOrder($user['uid'], [
            'order_id' => $orderId,
            'pay_type' => 'weixin',
            'paid' => 1,
            'pay_time' => time(),
            'total_price' => $amount,
            'pay_price' => $amount,
            'trade_no' => 'GW-' . $label . '-' . $this->token,
            'status' => 1,
        ]);
        $cart = $fixtures->createOrderCart((int)$order['id'], $user['uid'], ['product_id' => $product['id']]);
        $refund = $fixtures->createRefundOrder($user['uid'], (int)$order['id'], [
            'order_id' => $this->token . '-r-' . $label,
            'refund_type' => 1,
            'refund_price' => $amount,
            'cart_info' => json_encode([['id' => $cart['cart_id'], 'cart_num' => 1]]),
        ]);
        // The gateway really took this money.
        $this->gateway->seedOrder($orderId, 'paid', $amount);
        $this->gateway->simulatePayment($orderId, 'GW-' . $label . '-' . $this->token);

        return [(int)$refund['id'], (int)$order['id']];
    }

    /**
     * One more agreeable after-sale row for an order.
     */
    private function newAfterSale(int $orderId, string $amount): int
    {
        $row = BusinessSnapshot::order($orderId);
        $cart = BusinessSnapshot::cartInfos($orderId);
        $row2 = Db::name('store_order_refund')->insertGetId([
            'store_order_id' => $orderId,
            'uid' => (int)$row['uid'],
            'order_id' => $this->token . '-r2-' . substr(md5((string)random_int(1, 999999)), 0, 6),
            'refund_type' => 1,
            'refund_num' => 1,
            'refund_price' => $amount,
            'refunded_price' => '0.00',
            'cart_info' => json_encode([['id' => $cart[0]['cart_id'] ?? 1, 'cart_num' => 1]]),
            'add_time' => time(),
        ]);

        return (int)$row2;
    }

    /**
     * The identifier the gateway refund rows carry: trade number when the order
     * has one, otherwise the merchant order number.
     */
    private function refundGatewayKey(int $orderId): string
    {
        $order = BusinessSnapshot::order($orderId);

        return (string)($order['trade_no'] ?: $order['order_id']);
    }
}
