// Shared test helpers.
//
// The fixtures are the contracts' own examples (`tests/fixtures/contract-examples.json`,
// regenerated by `scripts/dump-contract-examples.mjs`), so a mapper is never tested
// against a payload the author of the test invented.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));

export const EXAMPLES = JSON.parse(
  fs.readFileSync(path.join(HERE, 'fixtures/contract-examples.json'), 'utf8'),
);

/** The example response for `METHOD path`, e.g. `example('GET /api/v1/cart')`. */
export function example(key) {
  const found = EXAMPLES[key];
  if (!found) throw new Error(`no contract example for ${key} — re-run scripts/dump-contract-examples.mjs`);
  return found.response;
}

/** The example request body, for the `fromPage*` direction. */
export function exampleBody(key) {
  const found = EXAMPLES[key];
  if (!found) throw new Error(`no contract example for ${key}`);
  return found.body;
}

/** Every value in the tree is a plain JSON value — no `undefined`, no `Date`, no NaN. */
export function assertRenderable(value, at = '$') {
  if (value === null) return;
  const type = typeof value;
  if (type === 'string' || type === 'boolean') return;
  if (type === 'number') {
    if (!Number.isFinite(value)) throw new Error(`${at} is ${value}`);
    return;
  }
  if (Array.isArray(value)) {
    value.forEach((v, i) => assertRenderable(v, `${at}[${i}]`));
    return;
  }
  if (type === 'object') {
    for (const [k, v] of Object.entries(value)) assertRenderable(v, `${at}.${k}`);
    return;
  }
  throw new Error(`${at} is a ${type}`);
}
