/**
 * Aggregates every `src/admin/menu/<domain>.menu.ts` into `menu.gen.ts`.
 *
 * Domains add a file; nothing shared is edited; the output is gitignored
 * (`*.gen.ts`), so parallel streams never conflict over it.
 *
 * Run by `pnpm --filter @shop/web gen` (and transitively by typecheck / lint /
 * test / build through turbo).
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const menuDir = join(here, '..', 'src', 'admin', 'menu');
const outFile = join(menuDir, 'menu.gen.ts');

const files = readdirSync(menuDir)
  .filter((name) => name.endsWith('.menu.ts'))
  .sort();

const imports = files
  .map((name, index) => `import m${index} from './${name.replace(/\.ts$/, '')}';`)
  .join('\n');

const spread = files.map((_name, index) => `  ...([m${index}].flat() as MenuNode[]),`).join('\n');

const banner = `// Generated by scripts/gen-menu.ts — do not edit, do not commit.
// Sources (${files.length}):
${files.map((name) => `//   ${name}`).join('\n')}
`;

const body = `${banner}
import type { MenuNode } from './types';

${imports}

/** Every declared menu node, unfiltered. Filter with \`filterMenu\` before rendering. */
export const menuRegistry: readonly MenuNode[] = [
${spread}
];
`;

let previous = '';
try {
  previous = readFileSync(outFile, 'utf8');
} catch {
  /* first run */
}
if (previous !== body) {
  writeFileSync(outFile, body, 'utf8');
}

process.stdout.write(`gen-menu: ${files.length} menu file(s) -> src/admin/menu/menu.gen.ts\n`);
