// Generated by scripts/gen-css-types.ts from service-grid.module.scss. Do not edit.
declare const styles: {
  readonly body: string;
  readonly cell: string;
  readonly cells: string;
  readonly cols4: string;
  readonly cols5: string;
  readonly glyph: string;
  readonly icon: string;
  readonly label: string;
  readonly title: string;
};
export default styles;
