// Generated by scripts/gen-css-types.ts from floating-contact.module.scss. Do not edit.
declare const styles: {
  readonly anchor: string;
  readonly button: string;
  readonly canvas: string;
  readonly face: string;
  readonly fixed: string;
  readonly icon: string;
  readonly inline: string;
  readonly label: string;
  readonly left: string;
  readonly note: string;
  readonly right: string;
};
export default styles;
