// Generated by scripts/gen-css-types.ts from frame.module.scss. Do not edit.
declare const styles: {
  readonly inner: string;
  readonly myLg: string;
  readonly myMd: string;
  readonly myNone: string;
  readonly mySm: string;
  readonly outer: string;
  readonly pxLg: string;
  readonly pxMd: string;
  readonly pxNone: string;
  readonly pxSm: string;
  readonly radiusLg: string;
  readonly radiusNone: string;
  readonly radiusSm: string;
};
export default styles;
