// Generated by scripts/gen-css-types.ts from list-head.module.scss. Do not edit.
declare const styles: {
  readonly chevron: string;
  readonly head: string;
  readonly more: string;
  readonly title: string;
};
export default styles;
