// Generated by scripts/gen-css-types.ts from hotspot-image.module.scss. Do not edit.
declare const styles: {
  readonly image: string;
  readonly spot: string;
  readonly stage: string;
};
export default styles;
