// Generated by scripts/gen-css-types.ts from order-entry.module.scss. Do not edit.
declare const styles: {
  readonly all: string;
  readonly badge: string;
  readonly body: string;
  readonly chevron: string;
  readonly entries: string;
  readonly entry: string;
  readonly head: string;
  readonly icon: string;
  readonly iconBox: string;
  readonly label: string;
  readonly title: string;
};
export default styles;
