import { readFileSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import type { DiyPageValue } from '@shop/contracts/diy/schema/page';

import { DomainError } from '../kernel/errors';
import { cleanDiyData, isRemovedStorefrontPage } from './compatibility';
import {
  assertProductLimits,
  countComponents,
  dehydrateDiyContent,
  nextContentVersion,
  validateDiyContent,
  versionOf,
} from './content';

/**
 * The fixtures live in `@shop/contracts` because that is where the schemas
 * that describe them live, and duplicating half a megabyte of production JSON
 * into a second package to avoid a relative path would be worse.
 */
const CONTRACT_FIXTURES = path.join(
  import.meta.dirname,
  '..',
  '..',
  '..',
  'contracts',
  'src',
  'diy',
  '__fixtures__',
);

function fixture<T = Record<string, unknown>>(name: string): T {
  return JSON.parse(readFileSync(path.join(CONTRACT_FIXTURES, name), 'utf8')) as T;
}

function pageValueOf(row: { value: unknown }): Record<string, unknown> {
  return typeof row.value === 'string'
    ? (JSON.parse(row.value) as Record<string, unknown>)
    : (row.value as Record<string, unknown>);
}

// ---------------------------------------------------------------------------
// cleanDiyData
// ---------------------------------------------------------------------------

/**
 * The expectations were generated by running the original PHP filter over these
 * exact inputs, so they are its own output, not a reading of it: saved pages
 * written by the old editor clean the same way here, and the proof stays a
 * plain unit test in CI.
 *
 * One normalisation: PHP cannot tell `{}` from `[]`, so where the input was an
 * object and the PHP returned `[]`, the expectation says `{}`.
 */
interface ParityCase {
  name: string;
  input: unknown;
  expected: unknown;
}

const parity = JSON.parse(
  readFileSync(path.join(import.meta.dirname, '__fixtures__', 'clean-parity.json'), 'utf8'),
) as ParityCase[];

describe('cleanDiyData — parity fixtures', () => {
  it('covers every branch of the filter', () => {
    expect(parity.length).toBeGreaterThanOrEqual(22);
  });

  it.each(parity.map((c) => [c.name, c] as const))('%s', (_name, testCase) => {
    expect(cleanDiyData(testCase.input)).toEqual(testCase.expected);
  });

  it('keeps key order, so a cleaned page still serialises byte for byte', () => {
    const page = { '3': { name: 'titles' }, '1': { name: 'menus' }, '2': { name: 'seckill' } };
    expect(JSON.stringify(cleanDiyData(page))).toBe(
      JSON.stringify({ '3': { name: 'titles' }, '1': { name: 'menus' } }),
    );
  });

  it('returns its input by identity when there is nothing to strip', () => {
    const page = { '1': { name: 'titles', link: '/pages/index/index' } };
    expect(cleanDiyData(page)).toBe(page);
  });

  it('never mutates the input', () => {
    const page = { '1': { name: 'seckill' }, '2': { name: 'titles' } };
    const before = JSON.stringify(page);
    cleanDiyData(page);
    expect(JSON.stringify(page)).toBe(before);
  });
});

describe('cleanDiyData — over the fixtures', () => {
  it('drops the five retired nodes and keeps the two live ones', () => {
    // It drops bargain, seckill, the 导航组 whose `info[1].value` points at
    // 积分, the coupon linking to 我的余额, and the node keyed `pointsMall`.
    // The swiperBg stays, and so does the titles node whose link is an external
    // `https://` URL.
    const cleaned = cleanDiyData(fixture('retired-components.json'));
    expect(Object.keys(cleaned)).toEqual(['1600000000000002', '1600000000000004']);
  });

  it('drops 秒杀 and 砍价 from the default home template', () => {
    const cleaned = cleanDiyData(fixture('moren-default-config.json'));
    const before = Object.keys(fixture('moren-default-config.json'));
    expect(before.filter((key) => !Object.keys(cleaned).includes(key))).toEqual([
      'seckill',
      'bargain',
    ]);
  });

  it('leaves the factory components alone', () => {
    const defaults = fixture('default-components.json');
    expect(cleanDiyData(defaults)).toBe(defaults);
  });

  it.each(['prod-6.json', 'prod-7.json', 'prod-8.json'])(
    '%s survives cleaning untouched',
    (name) => {
      const value = pageValueOf(fixture<{ value: unknown }>(name));
      expect(cleanDiyData(value)).toBe(value);
    },
  );
});

describe('isRemovedStorefrontPage', () => {
  it.each([
    ['/pages/points_mall/index', true],
    ['pages/points_mall/index', true],
    ['///pages/points_mall/index?id=3', true],
    ['/pages/index/index', false],
    ['https://example.test/pages/points_mall/index', false],
    ['', false],
    [null, false],
    [42, false],
  ])('%s -> %s', (url, expected) => {
    expect(isRemovedStorefrontPage(url)).toBe(expected);
  });
});

// ---------------------------------------------------------------------------
// content
// ---------------------------------------------------------------------------

describe('validateDiyContent', () => {
  it('hands back the caller’s own object, so the bytes never change', () => {
    const value = { '1': { name: 'titles', timestamp: 1, unknownKey: { deep: true } } };
    expect(validateDiyContent(value)).toBe(value);
  });

  it('accepts every production page', () => {
    for (const name of ['prod-6.json', 'prod-7.json', 'prod-8.json']) {
      const value = pageValueOf(fixture<{ value: unknown }>(name));
      expect(validateDiyContent(value)).toBe(value);
    }
  });

  it('reports the offending path instead of failing the whole save', () => {
    try {
      validateDiyContent({ '1': { name: 'titles', isHide: 'yes' } });
      expect.unreachable('should have thrown');
    } catch (error) {
      expect(DomainError.is(error)).toBe(true);
      const domain = error as DomainError;
      expect(domain.code).toBe('DIY_CONTENT_INVALID');
      expect(domain.details).toEqual([{ field: '1.isHide', message: expect.any(String) }]);
    }
  });

  it('refuses a page that is not an object', () => {
    expect(() => validateDiyContent([{ name: 'titles' }])).toThrow(DomainError);
  });
});

describe('dehydrateDiyContent', () => {
  it('turns the previewed products into ids, keeping every other key in place', () => {
    const node = {
      name: 'goodList',
      cname: '商品列表',
      timestamp: 1,
      tabConfig: { tabVal: 1 },
      goodsList: {
        max: 20,
        list: [
          { id: 7, store_name: 'a' },
          { id: 9, store_name: 'b' },
        ],
      },
      selectConfig: { activeValue: 0, list: [{ id: 3 }] },
      styleConfig: { tabVal: 0 },
    };
    const out = dehydrateDiyContent({ '1': node }) as Record<string, Record<string, unknown>>;
    expect(JSON.stringify(out['1'])).toBe(
      JSON.stringify({
        name: 'goodList',
        cname: '商品列表',
        timestamp: 1,
        tabConfig: { tabVal: 1 },
        goodsList: { max: 20, ids: [7, 9] },
        selectConfig: { activeValue: 0 },
        styleConfig: { tabVal: 0 },
      }),
    );
  });

  it('strips the article and promotion preview lists', () => {
    const value = {
      '1': { name: 'articleList', selectList: { list: [{ id: 1 }], max: 5 } },
      '2': { name: 'promotionList', productList: { list: [{ id: 2 }] } },
    };
    const out = dehydrateDiyContent(value) as Record<string, Record<string, unknown>>;
    expect(out['1']!.selectList).toEqual({ max: 5 });
    expect(out['2']!.productList).toEqual({});
  });

  it('is the identity when there is nothing hydrated', () => {
    const value = { '1': { name: 'titles' }, '2': { name: 'goodList', goodsList: { ids: [1] } } };
    expect(dehydrateDiyContent(value)).toBe(value);
  });

  it('leaves every production page byte-identical', () => {
    for (const name of ['prod-6.json', 'prod-7.json', 'prod-8.json']) {
      const value = pageValueOf(fixture<{ value: unknown }>(name)) as DiyPageValue;
      expect(JSON.stringify(dehydrateDiyContent(value))).toBe(JSON.stringify(value));
    }
  });
});

describe('assertProductLimits', () => {
  it('refuses more than the limit in automatic mode', () => {
    const value = { '1': { name: 'goodList', tabConfig: { tabVal: 0 }, numConfig: { val: 51 } } };
    expect(() => assertProductLimits(value)).toThrow(
      expect.objectContaining({ code: 'DIY_COMPONENT_LIMIT_EXCEEDED' }),
    );
  });

  it('refuses more than the limit in explicit mode', () => {
    const list = Array.from({ length: 51 }, (_, i) => ({ id: i + 1 }));
    const value = { '1': { name: 'goodList', tabConfig: { tabVal: 1 }, goodsList: { list } } };
    expect(() => assertProductLimits(value)).toThrow(DomainError);
  });

  it('allows exactly the limit', () => {
    const value = { '1': { name: 'goodList', tabConfig: { tabVal: 0 }, numConfig: { val: 50 } } };
    expect(() => assertProductLimits(value)).not.toThrow();
  });

  it('ignores components that are not product lists', () => {
    expect(() =>
      assertProductLimits({ '1': { name: 'titles', numConfig: { val: 900 } } }),
    ).not.toThrow();
  });
});

describe('versionOf / countComponents', () => {
  const at = new Date('2024-05-23T06:00:00.000Z');

  it('moves when the row is touched', () => {
    expect(versionOf({ updatedAt: at, content: null })).toBe('1716444000000-0');
    expect(versionOf({ updatedAt: new Date(at.getTime() + 1), content: null })).not.toBe(
      '1716444000000-0',
    );
  });

  it('moves when the content is saved again inside the same millisecond', () => {
    // The part `updated_at` cannot express. Without it, two saves a fraction of
    // a millisecond apart would share a token and the second would silently win.
    const first = versionOf({ updatedAt: at, content: { version: 'aaa' } });
    const second = versionOf({ updatedAt: at, content: { version: 'bbb' } });
    expect(first).not.toBe(second);
  });

  it('hands out a fresh envelope version every time', () => {
    expect(nextContentVersion(at)).not.toBe(nextContentVersion(at));
  });

  it('counts the nodes of a page', () => {
    expect(countComponents({ a: 1, b: 2 })).toBe(2);
    expect(countComponents(null)).toBe(0);
    expect(countComponents([])).toBe(0);
  });
});
