// Generated by scripts/gen-css-types.ts from title-bar.module.scss. Do not edit.
declare const styles: {
  readonly bar: string;
  readonly body: string;
  readonly center: string;
  readonly chevron: string;
  readonly heading: string;
  readonly more: string;
  readonly subtitle: string;
  readonly title: string;
};
export default styles;
