packages:
  - apps/*
  - packages/*
  - e2e/*
  - guards
allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.103.2'
  - '@tanstack/react-query@5.103.2'
