// Generated by scripts/gen-css-types.ts from follow-official-account.module.scss. Do not edit.
declare const styles: {
  readonly canvas: string;
  readonly placeholder: string;
  readonly text: string;
  readonly title: string;
};
export default styles;
