// Generated by scripts/gen-css-types.ts from search-bar.module.scss. Do not edit.
declare const styles: {
  readonly body: string;
  readonly field: string;
  readonly hit: string;
  readonly hot: string;
  readonly hotTrack: string;
  readonly icon: string;
  readonly placeholder: string;
  readonly round: string;
  readonly square: string;
  readonly sticky: string;
  readonly word: string;
};
export default styles;
