// Generated by scripts/gen-css-types.ts from spacer.module.scss. Do not edit.
declare const styles: {
  readonly dashed: string;
  readonly inset: string;
  readonly line: string;
  readonly space: string;
};
export default styles;
