// Generated by scripts/gen-css-types.ts from campaign-cards.module.scss. Do not edit.
declare const styles: {
  readonly badge: string;
  readonly body: string;
  readonly bottom: string;
  readonly button: string;
  readonly card: string;
  readonly cards: string;
  readonly foot: string;
  readonly image: string;
  readonly list: string;
  readonly media: string;
  readonly minor: string;
  readonly note: string;
  readonly price: string;
  readonly priceLabel: string;
  readonly prices: string;
  readonly scroll: string;
  readonly struck: string;
  readonly title: string;
  readonly track: string;
};
export default styles;
