// Generated by scripts/gen-css-types.ts from image-cube.module.scss. Do not edit.
declare const styles: {
  readonly box: string;
  readonly cell: string;
  readonly column: string;
  readonly fill: string;
  readonly gapLeft: string;
  readonly gapTop: string;
  readonly row: string;
  readonly rowCell: string;
  readonly rowImage: string;
  readonly split: string;
};
export default styles;
