// Generated by scripts/gen-css-types.ts from user-card.module.scss. Do not edit.
declare const styles: {
  readonly avatar: string;
  readonly background: string;
  readonly body: string;
  readonly hint: string;
  readonly identity: string;
  readonly name: string;
  readonly names: string;
  readonly pictured: string;
  readonly stat: string;
  readonly statLabel: string;
  readonly stats: string;
  readonly value: string;
};
export default styles;
