CREATE TABLE "wechat_mini_codes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wechat_mini_codes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"page" varchar(128) NOT NULL,
	"scene" varchar(32) NOT NULL,
	"storage_key" varchar(512) NOT NULL,
	"url" varchar(1024) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DROP INDEX "wechat_qrcode_categories_name_uq";--> statement-breakpoint
CREATE UNIQUE INDEX "wechat_mini_codes_page_scene_uq" ON "wechat_mini_codes" USING btree ("page","scene");--> statement-breakpoint
CREATE UNIQUE INDEX "wechat_qrcode_categories_name_uq" ON "wechat_qrcode_categories" USING btree ("name") WHERE deleted_at is null;