CREATE TYPE "public"."decor_designation" AS ENUM('home', 'user_center');--> statement-breakpoint
CREATE TYPE "public"."decor_documents_kind" AS ENUM('home', 'user_center', 'custom');--> statement-breakpoint
CREATE TABLE "decor_documents" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "decor_documents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"kind" "decor_documents_kind" NOT NULL,
	"name" varchar(50) NOT NULL,
	"title" varchar(30) DEFAULT '' NOT NULL,
	"draft" jsonb NOT NULL,
	"draft_version" integer DEFAULT 1 NOT NULL,
	"published_revision_id" bigint,
	"published_draft_version" integer,
	"designation" "decor_designation",
	"created_by_admin_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "decor_documents_draft_version_positive" CHECK ("decor_documents"."draft_version" >= 1),
	CONSTRAINT "decor_documents_designation_kind" CHECK ("decor_documents"."designation" is null or "decor_documents"."designation"::text = "decor_documents"."kind"::text),
	CONSTRAINT "decor_documents_designation_published" CHECK ("decor_documents"."designation" is null or "decor_documents"."published_revision_id" is not null),
	CONSTRAINT "decor_documents_designation_live" CHECK ("decor_documents"."designation" is null or "decor_documents"."deleted_at" is null)
);
--> statement-breakpoint
CREATE TABLE "decor_revisions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "decor_revisions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"document_id" bigint NOT NULL,
	"number" integer NOT NULL,
	"content" jsonb NOT NULL,
	"author_admin_id" bigint,
	"note" varchar(200) DEFAULT '' NOT NULL,
	"restored_from" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "decor_revisions_number_uq" UNIQUE("document_id","number"),
	CONSTRAINT "decor_revisions_document_id_uq" UNIQUE("document_id","id"),
	CONSTRAINT "decor_revisions_number_positive" CHECK ("decor_revisions"."number" >= 1),
	CONSTRAINT "decor_revisions_restored_from_earlier" CHECK ("decor_revisions"."restored_from" is null or ("decor_revisions"."restored_from" >= 1 and "decor_revisions"."restored_from" < "decor_revisions"."number"))
);
--> statement-breakpoint
ALTER TABLE "decor_documents" ADD CONSTRAINT "decor_documents_published_revision_fk" FOREIGN KEY ("id","published_revision_id") REFERENCES "public"."decor_revisions"("document_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "decor_revisions" ADD CONSTRAINT "decor_revisions_document_id_decor_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."decor_documents"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "decor_documents_kind_idx" ON "decor_documents" USING btree ("kind","updated_at") WHERE deleted_at is null;--> statement-breakpoint
CREATE UNIQUE INDEX "decor_documents_designation_uq" ON "decor_documents" USING btree ("designation") WHERE designation is not null and deleted_at is null;--> statement-breakpoint
-- Hand-written (drizzle-kit does not model triggers): published revisions are
-- append-only (DECOR-006). Row-level, so TRUNCATE in the test harness is unaffected.
CREATE FUNCTION "decor_revisions_immutable"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'decor_revisions is append-only: % refused', TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$;--> statement-breakpoint
CREATE TRIGGER "decor_revisions_immutable"
  BEFORE UPDATE OR DELETE ON "decor_revisions"
  FOR EACH ROW EXECUTE FUNCTION "decor_revisions_immutable"();
