CREATE TYPE "public"."wechat_trade_orders_confirm_source" AS ENUM('manual', 'auto', 'component');--> statement-breakpoint
CREATE TABLE "wechat_trade_orders" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wechat_trade_orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"order_id" bigint NOT NULL,
	"payment_attempt_id" bigint NOT NULL,
	"mch_id" varchar(64) NOT NULL,
	"out_trade_no" varchar(64) NOT NULL,
	"transaction_id" varchar(64) NOT NULL,
	"uploaded_at" timestamp with time zone,
	"all_delivered_at" timestamp with time zone,
	"corrected_at" timestamp with time zone,
	"confirmed_at" timestamp with time zone,
	"confirm_source" "wechat_trade_orders_confirm_source",
	"settled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "wechat_trade_orders_confirm_shape" CHECK (("wechat_trade_orders"."confirmed_at" is null) = ("wechat_trade_orders"."confirm_source" is null))
);
--> statement-breakpoint
ALTER TABLE "express_companies" ADD COLUMN "wechat_delivery_id" varchar(32);--> statement-breakpoint
ALTER TABLE "wechat_trade_orders" ADD CONSTRAINT "wechat_trade_orders_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wechat_trade_orders" ADD CONSTRAINT "wechat_trade_orders_payment_attempt_id_payment_attempts_id_fk" FOREIGN KEY ("payment_attempt_id") REFERENCES "public"."payment_attempts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "wechat_trade_orders_order_uq" ON "wechat_trade_orders" USING btree ("order_id");--> statement-breakpoint
CREATE UNIQUE INDEX "wechat_trade_orders_out_trade_no_uq" ON "wechat_trade_orders" USING btree ("out_trade_no");--> statement-breakpoint
CREATE INDEX "wechat_trade_orders_transaction_idx" ON "wechat_trade_orders" USING btree ("transaction_id");