CREATE TYPE "public"."content_security_checks_status" AS ENUM('pending', 'submitted', 'pass', 'review', 'risky', 'skipped');--> statement-breakpoint
CREATE TYPE "public"."content_security_checks_subject" AS ENUM('review_image', 'avatar');--> statement-breakpoint
CREATE TABLE "content_security_checks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "content_security_checks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"subject" "content_security_checks_subject" NOT NULL,
	"subject_id" bigint NOT NULL,
	"user_id" bigint,
	"media_url" varchar(1024) NOT NULL,
	"scene" smallint NOT NULL,
	"status" "content_security_checks_status" DEFAULT 'pending' NOT NULL,
	"trace_id" varchar(64),
	"label" integer,
	"action" varchar(32),
	"submitted_at" timestamp with time zone,
	"resolved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "content_security_checks_verdict_shape" CHECK ("content_security_checks"."status" not in ('pass','review','risky') or "content_security_checks"."resolved_at" is not null)
);
--> statement-breakpoint
ALTER TABLE "product_reviews" ADD COLUMN "moderation_reason" varchar(32);--> statement-breakpoint
ALTER TABLE "content_security_checks" ADD CONSTRAINT "content_security_checks_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "content_security_checks_trace_uq" ON "content_security_checks" USING btree ("trace_id") WHERE trace_id is not null;--> statement-breakpoint
CREATE INDEX "content_security_checks_subject_idx" ON "content_security_checks" USING btree ("subject","subject_id");