CREATE TABLE "admin_api_tokens" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_api_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"admin_id" bigint NOT NULL,
	"name" varchar(64) NOT NULL,
	"kind" varchar(8) NOT NULL,
	"token_hash" varchar(64) NOT NULL,
	"hint" varchar(16) NOT NULL,
	"refresh_hash" varchar(64),
	"client_id" varchar(64),
	"password_version" integer NOT NULL,
	"expires_at" timestamp with time zone,
	"refresh_expires_at" timestamp with time zone,
	"last_used_at" timestamp with time zone,
	"last_used_ip" varchar(64),
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "admin_api_tokens_kind_known" CHECK ("admin_api_tokens"."kind" in ('pat', 'oauth'))
);
--> statement-breakpoint
CREATE TABLE "oauth_clients" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth_clients_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"client_id" varchar(64) NOT NULL,
	"name" varchar(128) NOT NULL,
	"redirect_uris" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "audit_logs" ADD COLUMN "api_token_id" bigint;--> statement-breakpoint
ALTER TABLE "admin_api_tokens" ADD CONSTRAINT "admin_api_tokens_admin_id_admins_id_fk" FOREIGN KEY ("admin_id") REFERENCES "public"."admins"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "admin_api_tokens_token_hash_key" ON "admin_api_tokens" USING btree ("token_hash");--> statement-breakpoint
CREATE UNIQUE INDEX "admin_api_tokens_refresh_hash_key" ON "admin_api_tokens" USING btree ("refresh_hash");--> statement-breakpoint
CREATE INDEX "admin_api_tokens_admin_idx" ON "admin_api_tokens" USING btree ("admin_id");--> statement-breakpoint
CREATE UNIQUE INDEX "oauth_clients_client_id_key" ON "oauth_clients" USING btree ("client_id");--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_api_token_id_admin_api_tokens_id_fk" FOREIGN KEY ("api_token_id") REFERENCES "public"."admin_api_tokens"("id") ON DELETE set null ON UPDATE no action;