// Generated by scripts/gen-css-types.ts from video.module.scss. Do not edit.
declare const styles: {
  readonly frame: string;
  readonly hint: string;
  readonly play: string;
  readonly player: string;
  readonly poster: string;
  readonly square: string;
  readonly standard: string;
  readonly still: string;
  readonly triangle: string;
  readonly wide: string;
};
export default styles;
