// Generated by scripts/gen-css-types.ts from article-list.module.scss. Do not edit.
declare const styles: {
  readonly body: string;
  readonly cards: string;
  readonly cover: string;
  readonly empty: string;
  readonly item: string;
  readonly items: string;
  readonly meta: string;
  readonly rows: string;
  readonly summary: string;
  readonly text: string;
  readonly thumb: string;
  readonly title: string;
};
export default styles;
