import { createHash, createHmac } from 'node:crypto';
import {
  buildStorageKey,
  requireVariantKey,
  type PutOptions,
  type Storage,
  type StoredObject,
} from '../kernel/storage';

/**
 * S3-compatible object storage, signed by hand.
 *
 * It lives here rather than in the kernel because the kernel must stay
 * dependency-free, and so must this: `@aws-sdk/client-s3` is ~40 packages and
 * several MB for four HTTP verbs, and every S3-compatible vendor a CRMEB shop
 * actually uses — Aliyun OSS, Tencent COS, Qiniu, MinIO — speaks the same four
 * requests with the same SigV4 signature. `node:crypto` does the signing;
 * `fetch` does the talking.
 *
 * The **key is still generated by the server**, exactly as in the local driver.
 * The whole point of the `Storage` port is that a caller cannot choose a path.
 */

export interface S3Options {
  bucket: string;
  region: string;
  /** Vendor endpoint, e.g. `https://oss-cn-hangzhou.aliyuncs.com`. */
  endpoint?: string | undefined;
  accessKeyId: string;
  secretAccessKey: string;
  /** Where objects are publicly readable from, e.g. a CDN domain. */
  publicBaseUrl: string;
  /** `path` → `https://endpoint/bucket/key`, `virtual` → `https://bucket.endpoint/key`. */
  addressing?: 'path' | 'virtual';
  /** Required: domain code injects a `Clock`, it never reads the system time. */
  now: () => Date;
  fetchImpl?: typeof fetch;
  /**
   * Per-request ceilings, body included. Without one, a bucket that accepts the
   * connection and then stalls holds the upload request — and its advisory
   * lock and database connection — open until the socket gives up, minutes later.
   */
  timeoutMs?: { transfer?: number; control?: number } | undefined;
}

/** `PUT`/`GET`: a whole file moves, so this is generous. */
export const S3_TRANSFER_TIMEOUT_MS = 120_000;
/** `HEAD`/`DELETE`: nothing moves but headers. */
export const S3_CONTROL_TIMEOUT_MS = 15_000;

const SERVICE = 's3';
const UNSIGNED = 'UNSIGNED-PAYLOAD';

function sha256Hex(data: string | Uint8Array): string {
  return createHash('sha256').update(data).digest('hex');
}

function hmac(key: Buffer | string, data: string): Buffer {
  return createHmac('sha256', key).update(data, 'utf8').digest();
}

/**
 * RFC 3986 encoding. `encodeURIComponent` leaves `!'()*` alone and AWS does
 * not, which produces a signature mismatch on exactly the filenames nobody
 * tests with.
 */
function uriEncode(value: string, encodeSlash: boolean): string {
  let out = '';
  for (const char of value) {
    if (/[A-Za-z0-9\-._~]/.test(char)) out += char;
    else if (char === '/') out += encodeSlash ? '%2F' : '/';
    else {
      for (const byte of new TextEncoder().encode(char)) {
        out += `%${byte.toString(16).toUpperCase().padStart(2, '0')}`;
      }
    }
  }
  return out;
}

function amzDate(now: Date): { stamp: string; date: string } {
  const stamp = now
    .toISOString()
    .replace(/[-:]/g, '')
    .replace(/\.\d{3}/, '');
  return { stamp, date: stamp.slice(0, 8) };
}

export interface SignedRequest {
  url: string;
  headers: Record<string, string>;
}

/**
 * AWS Signature Version 4, header form.
 *
 * Exported so the unit test can check it against the published AWS test vector
 * rather than against itself — a signing routine that only agrees with its own
 * output is worth nothing.
 */
export function signS3Request(args: {
  method: string;
  host: string;
  path: string;
  query?: Record<string, string>;
  headers: Record<string, string>;
  payloadHash: string;
  region: string;
  accessKeyId: string;
  secretAccessKey: string;
  now: Date;
}): Record<string, string> {
  const { stamp, date } = amzDate(args.now);

  const headers: Record<string, string> = {
    ...args.headers,
    host: args.host,
    'x-amz-content-sha256': args.payloadHash,
    'x-amz-date': stamp,
  };

  const signedNames = Object.keys(headers)
    .map((name) => name.toLowerCase())
    .sort();
  const canonicalHeaders = signedNames
    .map((name) => {
      const entry = Object.entries(headers).find(([k]) => k.toLowerCase() === name);
      return `${name}:${String(entry?.[1] ?? '')
        .trim()
        .replace(/\s+/g, ' ')}\n`;
    })
    .join('');
  const signedHeaders = signedNames.join(';');

  const canonicalQuery = Object.keys(args.query ?? {})
    .sort()
    .map((key) => `${uriEncode(key, true)}=${uriEncode(args.query![key]!, true)}`)
    .join('&');

  const canonicalRequest = [
    args.method,
    uriEncode(args.path, false),
    canonicalQuery,
    canonicalHeaders,
    signedHeaders,
    args.payloadHash,
  ].join('\n');

  const scope = `${date}/${args.region}/${SERVICE}/aws4_request`;
  const stringToSign = ['AWS4-HMAC-SHA256', stamp, scope, sha256Hex(canonicalRequest)].join('\n');

  const signingKey = hmac(
    hmac(hmac(hmac(`AWS4${args.secretAccessKey}`, date), args.region), SERVICE),
    'aws4_request',
  );
  const signature = createHmac('sha256', signingKey).update(stringToSign, 'utf8').digest('hex');

  return {
    ...headers,
    authorization:
      `AWS4-HMAC-SHA256 Credential=${args.accessKeyId}/${scope}, ` +
      `SignedHeaders=${signedHeaders}, Signature=${signature}`,
  };
}

export class S3Error extends Error {
  constructor(
    readonly status: number,
    message: string,
  ) {
    super(message);
    this.name = 'S3Error';
  }
}

export function createS3Storage(options: S3Options): Storage {
  const now = options.now;
  const doFetch = options.fetchImpl ?? fetch;
  const addressing = options.addressing ?? 'path';
  const endpoint = new URL(
    options.endpoint ?? `https://${SERVICE}.${options.region}.amazonaws.com`,
  );
  const publicBase = options.publicBaseUrl.replace(/\/+$/, '');
  const transferTimeoutMs = options.timeoutMs?.transfer ?? S3_TRANSFER_TIMEOUT_MS;
  const controlTimeoutMs = options.timeoutMs?.control ?? S3_CONTROL_TIMEOUT_MS;

  const locate = (key: string): { url: string; host: string; path: string } => {
    const encoded = key
      .split('/')
      .map((part) => uriEncode(part, true))
      .join('/');
    if (addressing === 'virtual') {
      const host = `${options.bucket}.${endpoint.host}`;
      return { url: `${endpoint.protocol}//${host}/${encoded}`, host, path: `/${encoded}` };
    }
    const path = `/${options.bucket}/${encoded}`;
    return { url: `${endpoint.protocol}//${endpoint.host}${path}`, host: endpoint.host, path };
  };

  const send = async (
    method: string,
    key: string,
    body?: Uint8Array,
    extraHeaders: Record<string, string> = {},
  ): Promise<Response> => {
    const { url, host, path } = locate(key);
    const payloadHash = body ? sha256Hex(body) : sha256Hex('');
    const headers = signS3Request({
      method,
      host,
      path,
      headers: {
        ...extraHeaders,
        ...(body ? { 'content-length': String(body.byteLength) } : {}),
      },
      payloadHash,
      region: options.region,
      accessKeyId: options.accessKeyId,
      secretAccessKey: options.secretAccessKey,
      now: now(),
    });
    // `BodyInit` is a DOM name; this package does not load the DOM lib, and the
    // app that consumes it does, so the two disagree about whether a
    // `Uint8Array` is an acceptable body. Build the init untyped and hand it to
    // `fetch` once — it is a `Uint8Array` either way, and both agree on that.
    type FetchInit = NonNullable<Parameters<typeof fetch>[1]>;
    const timeoutMs = method === 'PUT' || method === 'GET' ? transferTimeoutMs : controlTimeoutMs;
    const init: Record<string, unknown> = {
      method,
      headers,
      signal: AbortSignal.timeout(timeoutMs),
    };
    if (body) init['body'] = body;
    return doFetch(url, init as unknown as FetchInit);
  };

  return {
    async put(rawBody, putOptions: PutOptions = {}): Promise<StoredObject> {
      const body = rawBody instanceof Uint8Array ? rawBody : new Uint8Array(rawBody);
      const key = buildStorageKey(now(), putOptions);
      const contentType = putOptions.contentType ?? 'application/octet-stream';
      const response = await send('PUT', key, body, {
        'content-type': contentType,
        ...(putOptions.maxAge === undefined
          ? {}
          : { 'cache-control': `public, max-age=${Math.floor(putOptions.maxAge)}` }),
      });
      if (!response.ok) {
        throw new S3Error(response.status, `S3 PUT ${response.status}`);
      }
      return {
        key,
        size: body.byteLength,
        contentType,
        sha256: createHash('sha256').update(body).digest('hex'),
      };
    },

    async putVariant(key, width, rawBody, contentType) {
      const variant = requireVariantKey(key, width);
      const body = rawBody instanceof Uint8Array ? rawBody : new Uint8Array(rawBody);
      const response = await send('PUT', variant, body, { 'content-type': contentType });
      if (!response.ok) {
        throw new S3Error(response.status, `S3 PUT ${response.status}`);
      }
      return variant;
    },

    async get(key) {
      const response = await send('GET', key);
      if (!response.ok) throw new S3Error(response.status, `S3 GET ${response.status}`);
      return Buffer.from(await response.arrayBuffer());
    },

    async delete(key) {
      const response = await send('DELETE', key);
      // 404 is success: the object is not there, which is what was asked for.
      if (!response.ok && response.status !== 404) {
        throw new S3Error(response.status, `S3 DELETE ${response.status}`);
      }
    },

    url(key) {
      return `${publicBase}/${key.replace(/^\/+/, '')}`;
    },

    async exists(key) {
      const response = await send('HEAD', key);
      return response.ok;
    },
  };
}

/** `UNSIGNED-PAYLOAD` is the right hash for a streamed PUT; kept for completeness. */
export const UNSIGNED_PAYLOAD = UNSIGNED;
