// Generated by scripts/gen-css-types.ts from nav-grid.module.scss. Do not edit.
declare const styles: {
  readonly body: string;
  readonly cell: string;
  readonly cells: string;
  readonly circle: string;
  readonly cols4: string;
  readonly cols5: string;
  readonly dot: string;
  readonly dotActive: string;
  readonly dots: string;
  readonly icon: string;
  readonly label: string;
  readonly pages: string;
};
export default styles;
