// Generated by scripts/gen-css-types.ts from product-grid.module.scss. Do not edit.
declare const styles: {
  readonly body: string;
  readonly card: string;
  readonly empty: string;
  readonly grid: string;
  readonly image: string;
  readonly lines1: string;
  readonly lines2: string;
  readonly market: string;
  readonly media: string;
  readonly minor: string;
  readonly price: string;
  readonly prices: string;
  readonly tag: string;
  readonly title: string;
};
export default styles;
