// Generated by scripts/gen-css-types.ts from product-cards.module.scss. Do not edit.
declare const styles: {
  readonly body: string;
  readonly card: string;
  readonly cards: string;
  readonly empty: string;
  readonly grid2: string;
  readonly grid3: string;
  readonly image: string;
  readonly lines1: string;
  readonly lines2: string;
  readonly list: string;
  readonly market: string;
  readonly media: string;
  readonly minor: string;
  readonly price: string;
  readonly prices: string;
  readonly scroll: string;
  readonly soldOut: string;
  readonly soldOutMark: string;
  readonly tag: string;
  readonly title: string;
  readonly track: string;
};
export default styles;
