// Generated by scripts/gen-css-types.ts from coupon-list.module.scss. Do not edit.
declare const styles: {
  readonly amount: string;
  readonly body: string;
  readonly button: string;
  readonly condition: string;
  readonly currency: string;
  readonly detail: string;
  readonly empty: string;
  readonly name: string;
  readonly outline: string;
  readonly scroll: string;
  readonly spent: string;
  readonly stack: string;
  readonly ticket: string;
  readonly track: string;
  readonly validity: string;
  readonly value: string;
};
export default styles;
