// Generated by scripts/gen-css-types.ts from carousel.module.scss. Do not edit.
declare const styles: {
  readonly image: string;
  readonly slide: string;
  readonly swiper: string;
};
export default styles;
