// Generated by scripts/gen-css-types.ts from newcomer-coupon.module.scss. Do not edit.
declare const styles: {
  readonly amount: string;
  readonly body: string;
  readonly button: string;
  readonly chip: string;
  readonly chips: string;
  readonly condition: string;
  readonly currency: string;
  readonly empty: string;
  readonly head: string;
  readonly note: string;
  readonly panel: string;
  readonly subtitle: string;
  readonly title: string;
  readonly titles: string;
};
export default styles;
