import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { build, type Plugin } from 'esbuild';

import { packageRoot, scssToAdminCss } from './css-modules';

/**
 * Builds the admin canvas artefacts:
 *
 *   dist/admin.js      the blocks + the DOM shim, ESM, React left external
 *   dist/admin.css     the shim's CSS + every block stylesheet, px → vw
 *   dist/admin-css.js  the same CSS as a default-exported string
 *
 * Why a prebuilt bundle rather than letting Next compile the sources: the
 * blocks' `*.module.scss` must be scaled px → vw for the canvas, and Next's CSS
 * pipeline cannot scope a PostCSS plugin to one package, nor produce class
 * names that match a stylesheet built anywhere else. esbuild compiles the CSS
 * modules (`local-css`) and the JS that references them in one pass, so the
 * class names always agree, and the admin needs neither sass nor an alias.
 * The mini-program compiles the same sources with Taro (px → rpx) and never
 * sees `dist/`.
 */

const dist = path.join(packageRoot, 'dist');

/** `*.module.scss` → sass → px→vw → handed to esbuild as a local-scoped CSS module. */
const scssModules: Plugin = {
  name: 'scss-modules',
  setup(builder) {
    builder.onLoad({ filter: /\.module\.scss$/ }, async (args) => ({
      contents: await scssToAdminCss(args.path),
      loader: 'local-css',
      resolveDir: path.dirname(args.path),
    }));
  },
};

export async function buildAdmin(): Promise<void> {
  rmSync(dist, { recursive: true, force: true });
  mkdirSync(dist, { recursive: true });
  await build({
    entryPoints: { admin: path.join(packageRoot, 'src/admin.ts') },
    outdir: dist,
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    jsx: 'automatic',
    // The host's React. Bundling one would put a second copy on the page.
    external: ['react', 'react-dom', 'react/jsx-runtime'],
    alias: { '@tarojs/components': path.join(packageRoot, 'src/dom/index.tsx') },
    plugins: [scssModules],
    // Deterministic, readable class names: `carousel_module_swiper`.
    minifyIdentifiers: false,
    legalComments: 'none',
    logLevel: 'warning',
  });
  const css = readFileSync(path.join(dist, 'admin.css'), 'utf8');
  writeFileSync(
    path.join(dist, 'admin-css.js'),
    `// Generated by scripts/build.ts: dist/admin.css as a string.\nexport default ${JSON.stringify(css)};\n`,
  );
}

if (import.meta.main) {
  await buildAdmin();
  console.log('storefront-blocks: dist/admin.{js,css} and dist/admin-css.js');
}
