import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { classNames, compileScss, findCssModules, packageRoot } from './css-modules';

/**
 * Writes `x.module.scss.d.ts` next to every `x.module.scss`, declaring exactly
 * the classes it defines. Committed (TypeScript and Taro both read them), and
 * rewritten only when they change; `css-types.test.ts` fails when one is stale.
 */

export function declarationFor(file: string): string {
  const names = classNames(compileScss(file));
  const lines = names.map((name) =>
    /^[A-Za-z_$][\w$]*$/.test(name)
      ? `  readonly ${name}: string;`
      : `  readonly '${name}': string;`,
  );
  return [
    `// Generated by scripts/gen-css-types.ts from ${path.basename(file)}. Do not edit.`,
    'declare const styles: {',
    ...lines,
    '};',
    'export default styles;',
    '',
  ].join('\n');
}

export function declarationPath(file: string): string {
  return `${file}.d.ts`;
}

function readOrEmpty(file: string): string {
  try {
    return readFileSync(file, 'utf8');
  } catch {
    return '';
  }
}

if (import.meta.main) {
  for (const file of findCssModules()) {
    const target = declarationPath(file);
    const next = declarationFor(file);
    if (readOrEmpty(target) !== next) {
      writeFileSync(target, next);
      console.log(`gen: ${path.relative(packageRoot, target)}`);
    }
  }
}
