#!/usr/bin/env bash
# What is deployed, and whether it is ready.
#
#   shop status
#
# Prints the release in `REVISION`, the image each application service is
# running (and what `deployment.env` pins, where the two differ), the last
# upgrade manifest, and then runs the readiness gate (lib/readiness.sh).
#
# Read-only: it starts nothing, stops nothing and writes nothing. Use it after
# a release, during a first-deploy smoke test, or to find out why a release
# was rolled back. It prints no setting but the image references.
#
# Exit codes: 0 every readiness check passed · 1 one did not · 2 misuse.
set -Eeuo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../common.sh
. "$here/../common.sh"
# shellcheck source=../readiness.sh
. "$here/../readiness.sh"

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h | --help)
      sed -n '2,14p' "$0"
      exit 0
      ;;
    *)
      warn "unknown argument: $1"
      exit 2
      ;;
  esac
done

require_settings

revision='<none>'
[ ! -s "$deploy_root/REVISION" ] || revision="$(head -n1 "$deploy_root/REVISION")"
say "release:   $revision"
say "directory: $deploy_root"

say ''
say 'running:'
for service in $APP_SERVICES; do
  role="$(printf '%s' "$service" | tr '[:lower:]' '[:upper:]')"
  pinned="$(setting "NEXT_${role}_IMAGE")"
  if captured="$(running_image_ref "$service")"; then
    running="${captured%% *}"
    say "  $service: $running"
    [ "$running" = "$pinned" ] || say "    but deployment.env pins $pinned"
  else
    say "  $service: <not running>; deployment.env pins $pinned"
  fi
done

say ''
backup_dir="$(backup_dir)"
# shellcheck disable=SC2012  # the names are generated by `shop upgrade`.
manifest="$(ls -t "$backup_dir"/upgrade-*.manifest 2>/dev/null | head -n1 || true)"
if [ -n "$manifest" ]; then
  say "last upgrade: $manifest"
  # A manifest holds image references, paths and outcomes, never a credential.
  sed 's/^/  /' "$manifest"
else
  say "last upgrade: <none in $backup_dir>"
fi

say ''
readiness_gate
