import fs from 'node:fs';
import { defineCheck, fail, note, result, type Finding } from '../framework';
import { diffSurfaces, storefrontSurface, type Surface } from '../lib/api-compat';
import { apiBaselineFile, openapiFile, rel } from '../lib/paths';

/**
 * The storefront API (`/api/v1/**`) only grows (docs/mini/cutover.md §5).
 *
 * `guards/baselines/storefront-api.json` is the storefront part of the OpenAPI
 * document as the last released mini-program version saw it. The check diffs
 * today's generated document against it (`lib/api-compat.ts` says what counts
 * as breaking, per direction) and reports every change an installed client
 * would trip over.
 *
 * The baseline is refreshed only when a mini-program version is released:
 *
 *     pnpm --filter @shop/guards api-compat:refresh --release <apps/mini version>
 *
 * Before the first release nothing is in shoppers' hands, so the baseline is a
 * snapshot (`"release": null`), refreshed freely with `--unreleased`, and the
 * check is report-only.
 */

/**
 * **The switch.** `false`: a breaking change is printed as a note and the
 * check passes (report-only, until the first mini-program release). `true`:
 * a breaking change fails `pnpm guards`. Flipped in the same commit that
 * refreshes the baseline with `--release` for the first release
 * (docs/mini/cutover.md §5).
 */
export const ENFORCED = false;

export interface Baseline {
  $comment: string;
  /** The mini-program version this surface was released with; `null` before the first release. */
  release: string | null;
  operations: Surface;
}

export const BASELINE_COMMENT =
  'Generated by `pnpm --filter @shop/guards api-compat:refresh`; do not edit. ' +
  'The storefront API (/api/v1) as the released mini-program sees it: the `api-compat` guard ' +
  'fails on anything that would break that version. See docs/mini/cutover.md §5.';

export function readBaseline(): Baseline | null {
  if (!fs.existsSync(apiBaselineFile)) return null;
  return JSON.parse(fs.readFileSync(apiBaselineFile, 'utf8')) as Baseline;
}

/** Today's storefront surface, from the document `pnpm gen` wrote. */
export function readCurrentSurface(): Surface | null {
  if (!fs.existsSync(openapiFile)) return null;
  return storefrontSurface(JSON.parse(fs.readFileSync(openapiFile, 'utf8')));
}

const NAME = 'api-compat';
const TITLE =
  'the storefront API only grows: nothing a released mini-program version uses is removed or narrowed';

export const apiCompat = defineCheck(NAME, TITLE, () => {
  const name = NAME;
  const title = TITLE;
  const baseline = readBaseline();
  const current = readCurrentSurface();
  if (!baseline) {
    return result(name, title, 'no baseline', [
      fail(
        rel(apiBaselineFile),
        'missing: run `pnpm --filter @shop/guards api-compat:refresh --unreleased` (before the first release) or `--release <version>`',
      ),
    ]);
  }
  if (!current) {
    return result(name, title, 'no OpenAPI document', [
      fail(rel(openapiFile), 'missing: run `pnpm gen` first'),
    ]);
  }

  const changes = diffSurfaces(baseline.operations, current);
  const breaking = changes.filter((c) => c.severity === 'breaking');
  const findings: Finding[] = [];
  if (ENFORCED && baseline.release === null) {
    findings.push(
      fail(
        rel(apiBaselineFile),
        'enforced against an unreleased snapshot: refresh with `--release <version>` at the release that flips the switch',
      ),
    );
  }
  for (const change of changes) {
    if (change.severity === 'breaking') {
      findings.push(
        ENFORCED
          ? fail(change.op, `${change.at}: ${change.message}`)
          : note(change.op, `[breaking, report-only] ${change.at}: ${change.message}`),
      );
    } else {
      findings.push(note(change.op, `${change.at}: ${change.message}`));
    }
  }

  const against =
    baseline.release === null ? 'the unreleased snapshot' : `release ${baseline.release}`;
  const added = Object.keys(current).length - Object.keys(baseline.operations).length;
  return result(
    name,
    title,
    `${Object.keys(current).length} storefront operation(s) against ${against} ` +
      `(${added >= 0 ? '+' : ''}${added}); ${breaking.length} breaking change(s)` +
      (ENFORCED ? '' : ', report-only'),
    findings,
  );
});
