// Generated by scripts/gen-css-types.ts from product-tabs.module.scss. Do not edit.
declare const styles: {
  readonly active: string;
  readonly label: string;
  readonly tab: string;
  readonly tabs: string;
};
export default styles;
